/* ============================================================
   WasGegessen? – Grundnahrungsmittel

   Open Food Facts kennt fast nur verpackte Ware mit Barcode. Lose
   Kartoffeln, ein Ei oder ein Stück Butter stehen dort nicht oder nur
   als zufälliges Markenprodukt. Diese Liste schließt die Lücke: die
   Dinge, die man täglich isst, mit verlässlichen Durchschnittswerten.

   Sie steckt fest in der App – die Suche liefert sie sofort, auch
   offline und auch dann, wenn Open Food Facts gerade nicht antwortet.

   Werte je 100 g bzw. 100 ml, nach europäischer Kennzeichnung:
   Kohlenhydrate OHNE Ballaststoffe (so steht es auch auf deutschen
   Packungen). Quelle sind die üblichen Durchschnittswerte für
   unverarbeitete Lebensmittel; Markenware kann abweichen.

   `alias` sind zusätzliche Suchwörter (Plural, Synonyme, Dialekt).
   `portionen` nur dort, wo die Standardportionen aus daten.js nicht
   passen – sonst greift automatisch portionenFuer().
   ============================================================ */

const GRUNDNAHRUNG = [

  /* ---------- Kartoffeln und Beilagen ---------- */
  { gruppe:'Beilagen', name:'Kartoffeln, gekocht', alias:['kartoffel','salzkartoffeln','pellkartoffeln','erdapfel'],
    kcal:80, eiweiss:2.0, fett:0.1, kh:16.5,
    portionen:[{name:'1 mittelgroße Kartoffel',gramm:100},{name:'1 Portion',gramm:200},{name:'1 große Portion',gramm:300}] },
  { gruppe:'Beilagen', name:'Kartoffeln, roh', alias:['kartoffel roh','rohe kartoffeln'],
    kcal:77, eiweiss:2.0, fett:0.1, kh:15.4,
    portionen:[{name:'1 mittelgroße Kartoffel',gramm:100},{name:'1 Portion',gramm:200}] },
  { gruppe:'Beilagen', name:'Bratkartoffeln', alias:['bratkartoffel'],
    kcal:153, eiweiss:2.4, fett:7.5, kh:18.0 },
  { gruppe:'Beilagen', name:'Pommes frites', alias:['pommes','fritten'],
    kcal:290, eiweiss:3.5, fett:14.5, kh:36.0,
    portionen:[{name:'1 kleine Portion',gramm:100},{name:'1 Portion',gramm:150},{name:'1 große Portion',gramm:250}] },
  { gruppe:'Beilagen', name:'Kartoffelpüree', alias:['kartoffelbrei','püree','stampfkartoffeln'],
    kcal:88, eiweiss:2.1, fett:2.5, kh:13.5 },
  { gruppe:'Beilagen', name:'Kartoffelsalat', alias:[],
    kcal:140, eiweiss:1.8, fett:8.0, kh:14.5 },
  { gruppe:'Beilagen', name:'Süßkartoffel, gekocht', alias:['süßkartoffeln','batate'],
    kcal:90, eiweiss:1.6, fett:0.1, kh:20.0 },
  { gruppe:'Beilagen', name:'Reis, gekocht', alias:['reis','weißer reis','basmatireis','langkornreis'],
    kcal:130, eiweiss:2.7, fett:0.3, kh:28.0,
    portionen:[{name:'1 Tasse',gramm:180},{name:'1 Portion',gramm:200},{name:'1 Teller',gramm:300}] },
  { gruppe:'Beilagen', name:'Reis, roh', alias:['reis roh','roher reis'],
    kcal:349, eiweiss:7.0, fett:0.6, kh:77.0,
    portionen:[{name:'1 Portion trocken',gramm:75},{name:'1 große Portion trocken',gramm:100}] },
  { gruppe:'Beilagen', name:'Vollkornreis, gekocht', alias:['naturreis','brauner reis'],
    kcal:111, eiweiss:2.6, fett:0.9, kh:22.0 },
  { gruppe:'Beilagen', name:'Nudeln, gekocht', alias:['nudel','pasta','spaghetti','penne','makkaroni','fusilli'],
    kcal:158, eiweiss:5.8, fett:0.9, kh:31.0,
    portionen:[{name:'1 Portion',gramm:250},{name:'1 kleine Portion',gramm:180},{name:'1 großer Teller',gramm:350}] },
  { gruppe:'Beilagen', name:'Nudeln, roh', alias:['nudeln trocken','pasta roh'],
    kcal:350, eiweiss:12.0, fett:1.5, kh:71.0,
    portionen:[{name:'1 Portion trocken',gramm:100},{name:'1 kleine Portion trocken',gramm:75}] },
  { gruppe:'Beilagen', name:'Vollkornnudeln, gekocht', alias:['vollkornpasta'],
    kcal:124, eiweiss:5.0, fett:0.9, kh:23.0 },
  { gruppe:'Beilagen', name:'Couscous, gekocht', alias:['kuskus'],
    kcal:112, eiweiss:3.8, fett:0.2, kh:23.0 },
  { gruppe:'Beilagen', name:'Bulgur, gekocht', alias:[],
    kcal:83, eiweiss:3.1, fett:0.2, kh:16.0 },
  { gruppe:'Beilagen', name:'Quinoa, gekocht', alias:[],
    kcal:120, eiweiss:4.4, fett:1.9, kh:18.5 },
  { gruppe:'Beilagen', name:'Knödel', alias:['kloß','klöße','knödeln','semmelknödel'],
    kcal:130, eiweiss:3.5, fett:2.0, kh:24.0,
    portionen:[{name:'1 Knödel',gramm:90},{name:'2 Knödel',gramm:180}] },
  { gruppe:'Beilagen', name:'Gnocchi', alias:[],
    kcal:160, eiweiss:4.0, fett:1.0, kh:33.0 },

  /* ---------- Brot und Backwaren ---------- */
  { gruppe:'Brot', name:'Vollkornbrot', alias:['vollkorn brot'],
    kcal:210, eiweiss:7.0, fett:1.5, kh:38.0,
    portionen:[{name:'1 Scheibe',gramm:50},{name:'1 dicke Scheibe',gramm:70}] },
  { gruppe:'Brot', name:'Mischbrot', alias:['graubrot','bauernbrot','brot'],
    kcal:250, eiweiss:7.5, fett:1.2, kh:49.0,
    portionen:[{name:'1 Scheibe',gramm:45},{name:'1 dicke Scheibe',gramm:65}] },
  { gruppe:'Brot', name:'Roggenbrot', alias:['roggenmischbrot'],
    kcal:220, eiweiss:6.5, fett:1.2, kh:42.0,
    portionen:[{name:'1 Scheibe',gramm:50}] },
  { gruppe:'Brot', name:'Weißbrot', alias:['weizenbrot','ciabatta'],
    kcal:265, eiweiss:8.5, fett:3.2, kh:49.0,
    portionen:[{name:'1 Scheibe',gramm:40}] },
  { gruppe:'Brot', name:'Toastbrot', alias:['toast','sandwichtoast'],
    kcal:280, eiweiss:8.0, fett:4.0, kh:50.0,
    portionen:[{name:'1 Scheibe',gramm:25},{name:'2 Scheiben',gramm:50}] },
  { gruppe:'Brot', name:'Brötchen', alias:['semmel','weck','schrippe','rundstück'],
    kcal:280, eiweiss:9.0, fett:2.0, kh:55.0,
    portionen:[{name:'1 Brötchen',gramm:60},{name:'1 halbes Brötchen',gramm:30}] },
  { gruppe:'Brot', name:'Vollkornbrötchen', alias:['körnerbrötchen'],
    kcal:250, eiweiss:9.5, fett:3.5, kh:42.0,
    portionen:[{name:'1 Brötchen',gramm:70}] },
  { gruppe:'Brot', name:'Baguette', alias:['stangenweißbrot'],
    kcal:270, eiweiss:8.5, fett:1.5, kh:54.0,
    portionen:[{name:'1 Stück',gramm:75},{name:'1 halbes Baguette',gramm:125}] },
  { gruppe:'Brot', name:'Pumpernickel', alias:[],
    kcal:190, eiweiss:6.0, fett:1.2, kh:36.0,
    portionen:[{name:'1 Scheibe',gramm:40}] },
  { gruppe:'Brot', name:'Knäckebrot', alias:['knäcke'],
    kcal:340, eiweiss:10.0, fett:1.5, kh:66.0,
    portionen:[{name:'1 Scheibe',gramm:10}] },
  { gruppe:'Brot', name:'Zwieback', alias:[],
    kcal:380, eiweiss:10.0, fett:4.0, kh:74.0,
    portionen:[{name:'1 Stück',gramm:10}] },
  { gruppe:'Brot', name:'Croissant', alias:['hörnchen'],
    kcal:406, eiweiss:8.0, fett:21.0, kh:45.0,
    portionen:[{name:'1 Croissant',gramm:60}] },
  { gruppe:'Brot', name:'Laugenbrezel', alias:['brezel','brezn'],
    kcal:290, eiweiss:9.0, fett:3.0, kh:55.0,
    portionen:[{name:'1 Brezel',gramm:90}] },

  /* ---------- Frühstück ---------- */
  { gruppe:'Frühstück', name:'Haferflocken', alias:['hafer','porridge','haferbrei'],
    kcal:372, eiweiss:13.5, fett:7.0, kh:58.7,
    portionen:[{name:'1 Portion',gramm:50},{name:'1 Schüssel',gramm:80},{name:'1 Esslöffel',gramm:10}] },
  { gruppe:'Frühstück', name:'Müsli', alias:['früchtemüsli','knuspermüsli','granola'],
    kcal:360, eiweiss:9.0, fett:8.0, kh:60.0,
    portionen:[{name:'1 Portion',gramm:50},{name:'1 Schüssel',gramm:80}] },
  { gruppe:'Frühstück', name:'Cornflakes', alias:['frühstücksflocken'],
    kcal:378, eiweiss:7.5, fett:0.9, kh:84.0,
    portionen:[{name:'1 Portion',gramm:40}] },
  { gruppe:'Frühstück', name:'Grieß', alias:['hartweizengrieß','grießbrei'],
    kcal:350, eiweiss:11.0, fett:1.0, kh:73.0 },

  /* ---------- Milch und Milchprodukte ---------- */
  { gruppe:'Milchprodukte', name:'Vollmilch 3,5 %', alias:['milch','vollmilch'], fluessig:true,
    kcal:64, eiweiss:3.4, fett:3.6, kh:4.7,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 Tasse',gramm:150},{name:'1 Schuss',gramm:30}] },
  { gruppe:'Milchprodukte', name:'Fettarme Milch 1,5 %', alias:['fettarme milch','magermilch 1,5'], fluessig:true,
    kcal:47, eiweiss:3.4, fett:1.5, kh:4.9,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 Tasse',gramm:150}] },
  { gruppe:'Milchprodukte', name:'Magermilch 0,3 %', alias:['magermilch','entrahmte milch'], fluessig:true,
    kcal:35, eiweiss:3.5, fett:0.3, kh:4.9 },
  { gruppe:'Milchprodukte', name:'Hafermilch', alias:['haferdrink'], fluessig:true,
    kcal:45, eiweiss:0.8, fett:1.5, kh:6.6 },
  { gruppe:'Milchprodukte', name:'Mandelmilch', alias:['mandeldrink'], fluessig:true,
    kcal:24, eiweiss:0.5, fett:1.6, kh:2.4 },
  { gruppe:'Milchprodukte', name:'Sojamilch', alias:['sojadrink'], fluessig:true,
    kcal:39, eiweiss:3.3, fett:1.8, kh:2.5 },
  { gruppe:'Milchprodukte', name:'Buttermilch', alias:[], fluessig:true,
    kcal:37, eiweiss:3.5, fett:0.5, kh:4.0 },
  { gruppe:'Milchprodukte', name:'Joghurt natur 3,5 %', alias:['joghurt','naturjoghurt'],
    kcal:63, eiweiss:3.5, fett:3.5, kh:4.7,
    portionen:[{name:'1 Becher',gramm:150},{name:'1 großer Becher',gramm:250}] },
  { gruppe:'Milchprodukte', name:'Magerjoghurt 0,1 %', alias:['magerjoghurt','fettarmer joghurt'],
    kcal:38, eiweiss:4.3, fett:0.1, kh:5.0,
    portionen:[{name:'1 Becher',gramm:150}] },
  { gruppe:'Milchprodukte', name:'Griechischer Joghurt 10 %', alias:['griechischer joghurt'],
    kcal:115, eiweiss:5.0, fett:10.0, kh:3.5,
    portionen:[{name:'1 Becher',gramm:150}] },
  { gruppe:'Milchprodukte', name:'Skyr', alias:[],
    kcal:63, eiweiss:11.0, fett:0.2, kh:4.0,
    portionen:[{name:'1 Becher',gramm:150},{name:'1 großer Becher',gramm:450}] },
  { gruppe:'Milchprodukte', name:'Magerquark', alias:['quark','speisequark mager'],
    kcal:67, eiweiss:12.0, fett:0.3, kh:4.1,
    portionen:[{name:'1 Packung',gramm:250},{name:'1 Portion',gramm:125}] },
  { gruppe:'Milchprodukte', name:'Speisequark 20 %', alias:['quark 20'],
    kcal:109, eiweiss:11.5, fett:5.1, kh:3.2 },
  { gruppe:'Milchprodukte', name:'Schlagsahne 30 %', alias:['sahne','schlagobers'],
    kcal:292, eiweiss:2.4, fett:30.0, kh:3.3,
    portionen:[{name:'1 Esslöffel',gramm:15},{name:'1 Becher',gramm:200}] },
  { gruppe:'Milchprodukte', name:'Schmand 24 %', alias:['saure sahne','sauerrahm'],
    kcal:237, eiweiss:2.8, fett:24.0, kh:3.3 },
  { gruppe:'Milchprodukte', name:'Crème fraîche', alias:['creme fraiche'],
    kcal:292, eiweiss:2.4, fett:30.0, kh:3.0 },
  { gruppe:'Milchprodukte', name:'Frischkäse', alias:['doppelrahmfrischkäse','philadelphia'],
    kcal:253, eiweiss:6.0, fett:24.0, kh:3.0,
    portionen:[{name:'1 Esslöffel',gramm:20},{name:'1 Portion fürs Brot',gramm:15}] },
  { gruppe:'Milchprodukte', name:'Hüttenkäse', alias:['körniger frischkäse','cottage cheese'],
    kcal:98, eiweiss:12.0, fett:4.3, kh:3.0,
    portionen:[{name:'1 Becher',gramm:200}] },
  { gruppe:'Milchprodukte', name:'Gouda', alias:['käse','schnittkäse'],
    kcal:356, eiweiss:25.0, fett:28.0, kh:0,
    portionen:[{name:'1 Scheibe',gramm:30},{name:'1 Würfel',gramm:20}] },
  { gruppe:'Milchprodukte', name:'Emmentaler', alias:[],
    kcal:380, eiweiss:28.0, fett:29.0, kh:0,
    portionen:[{name:'1 Scheibe',gramm:30}] },
  { gruppe:'Milchprodukte', name:'Mozzarella', alias:[],
    kcal:254, eiweiss:18.0, fett:20.0, kh:1.0,
    portionen:[{name:'1 Kugel',gramm:125},{name:'1 halbe Kugel',gramm:62}] },
  { gruppe:'Milchprodukte', name:'Feta', alias:['schafskäse','hirtenkäse'],
    kcal:264, eiweiss:14.0, fett:21.0, kh:4.0,
    portionen:[{name:'1 Portion',gramm:50}] },
  { gruppe:'Milchprodukte', name:'Parmesan', alias:['parmigiano','hartkäse'],
    kcal:392, eiweiss:36.0, fett:26.0, kh:0,
    portionen:[{name:'1 Esslöffel gerieben',gramm:8},{name:'1 Portion gerieben',gramm:20}] },
  { gruppe:'Milchprodukte', name:'Camembert', alias:['brie','weichkäse'],
    kcal:300, eiweiss:20.0, fett:24.0, kh:0.5,
    portionen:[{name:'1 Stück',gramm:30}] },
  { gruppe:'Milchprodukte', name:'Butter', alias:['süßrahmbutter','markenbutter'],
    kcal:741, eiweiss:0.7, fett:82.0, kh:0.6,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:15},{name:'fürs Brot',gramm:10},{name:'1 Stück (250 g)',gramm:250}] },
  { gruppe:'Milchprodukte', name:'Margarine', alias:[],
    kcal:720, eiweiss:0.2, fett:80.0, kh:0.4,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:15},{name:'fürs Brot',gramm:10}] },

  /* ---------- Eier ---------- */
  { gruppe:'Eier', name:'Hühnerei', alias:['ei','eier','frühstücksei','spiegelei','rührei gekocht'],
    kcal:143, eiweiss:12.6, fett:9.5, kh:0.7,
    portionen:[{name:'1 Ei (Größe M)',gramm:58},{name:'1 Ei (Größe L)',gramm:68},{name:'1 Ei (Größe S)',gramm:48},{name:'2 Eier (M)',gramm:116}] },
  { gruppe:'Eier', name:'Eiklar', alias:['eiweiß','eiweiss'],
    kcal:52, eiweiss:11.0, fett:0.2, kh:0.7,
    portionen:[{name:'1 Eiklar',gramm:33}] },
  { gruppe:'Eier', name:'Eigelb', alias:['eidotter','dotter'],
    kcal:322, eiweiss:16.0, fett:27.0, kh:3.6,
    portionen:[{name:'1 Eigelb',gramm:18}] },

  /* ---------- Fleisch und Wurst ---------- */
  { gruppe:'Fleisch', name:'Hähnchenbrust', alias:['hühnerbrust','hähnchen','geflügel','pouletbrust'],
    kcal:107, eiweiss:23.0, fett:1.3, kh:0,
    portionen:[{name:'1 Filet',gramm:150},{name:'1 kleines Filet',gramm:100}] },
  { gruppe:'Fleisch', name:'Hähnchenschenkel', alias:['hühnerkeule','hähnchenkeule'],
    kcal:180, eiweiss:19.0, fett:11.0, kh:0,
    portionen:[{name:'1 Schenkel',gramm:130}] },
  { gruppe:'Fleisch', name:'Putenbrust', alias:['pute','truthahn'],
    kcal:105, eiweiss:24.0, fett:1.0, kh:0,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Fleisch', name:'Rinderhackfleisch', alias:['hackfleisch rind','rinderhack','tatar'],
    kcal:150, eiweiss:21.0, fett:7.0, kh:0,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Packung',gramm:500}] },
  { gruppe:'Fleisch', name:'Hackfleisch gemischt', alias:['hackfleisch','gehacktes','mett'],
    kcal:240, eiweiss:18.0, fett:18.0, kh:0,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Packung',gramm:500}] },
  { gruppe:'Fleisch', name:'Schweineschnitzel, roh', alias:['schnitzel','schweinefleisch'],
    kcal:108, eiweiss:22.0, fett:2.0, kh:0,
    portionen:[{name:'1 Schnitzel',gramm:150}] },
  { gruppe:'Fleisch', name:'Schnitzel, paniert', alias:['wiener schnitzel','paniertes schnitzel'],
    kcal:250, eiweiss:17.0, fett:14.0, kh:14.0,
    portionen:[{name:'1 Schnitzel',gramm:180}] },
  { gruppe:'Fleisch', name:'Rindersteak', alias:['steak','rumpsteak','rindfleisch'],
    kcal:150, eiweiss:22.0, fett:6.5, kh:0,
    portionen:[{name:'1 Steak',gramm:200}] },
  { gruppe:'Fleisch', name:'Schweinebauch', alias:['bauchspeck'],
    kcal:350, eiweiss:17.0, fett:31.0, kh:0 },
  { gruppe:'Fleisch', name:'Frühstücksspeck', alias:['speck','bacon'],
    kcal:400, eiweiss:15.0, fett:38.0, kh:0,
    portionen:[{name:'1 Scheibe',gramm:15}] },
  { gruppe:'Fleisch', name:'Kochschinken', alias:['schinken','vorderschinken'],
    kcal:110, eiweiss:20.0, fett:3.0, kh:0.5,
    portionen:[{name:'1 Scheibe',gramm:25}] },
  { gruppe:'Fleisch', name:'Salami', alias:[],
    kcal:380, eiweiss:20.0, fett:33.0, kh:1.0,
    portionen:[{name:'1 Scheibe',gramm:10}] },
  { gruppe:'Fleisch', name:'Bratwurst', alias:['rostbratwurst','grillwurst'],
    kcal:300, eiweiss:13.0, fett:27.0, kh:1.0,
    portionen:[{name:'1 Wurst',gramm:120}] },
  { gruppe:'Fleisch', name:'Wiener Würstchen', alias:['würstchen','frankfurter','bockwurst'],
    kcal:280, eiweiss:12.0, fett:25.0, kh:0.5,
    portionen:[{name:'1 Würstchen',gramm:50},{name:'2 Würstchen',gramm:100}] },
  { gruppe:'Fleisch', name:'Leberwurst', alias:[],
    kcal:320, eiweiss:13.0, fett:29.0, kh:1.5,
    portionen:[{name:'fürs Brot',gramm:20}] },
  { gruppe:'Fleisch', name:'Currywurst', alias:[],
    kcal:290, eiweiss:11.0, fett:24.0, kh:7.0,
    portionen:[{name:'1 Portion',gramm:180}] },

  /* ---------- Fisch ---------- */
  { gruppe:'Fisch', name:'Lachs', alias:['lachsfilet','räucherlachs'],
    kcal:208, eiweiss:20.0, fett:13.0, kh:0,
    portionen:[{name:'1 Filet',gramm:140},{name:'1 Portion',gramm:120}] },
  { gruppe:'Fisch', name:'Thunfisch in Wasser', alias:['thunfisch','tunfisch'],
    kcal:110, eiweiss:25.0, fett:1.0, kh:0,
    portionen:[{name:'1 Dose (abgetropft)',gramm:150}] },
  { gruppe:'Fisch', name:'Forelle', alias:[],
    kcal:119, eiweiss:20.0, fett:4.0, kh:0,
    portionen:[{name:'1 Forelle',gramm:200}] },
  { gruppe:'Fisch', name:'Kabeljau', alias:['dorsch','seelachs'],
    kcal:82, eiweiss:18.0, fett:0.7, kh:0,
    portionen:[{name:'1 Filet',gramm:150}] },
  { gruppe:'Fisch', name:'Hering', alias:['matjes','bismarckhering'],
    kcal:200, eiweiss:18.0, fett:14.0, kh:0 },
  { gruppe:'Fisch', name:'Garnelen', alias:['shrimps','scampi'],
    kcal:99, eiweiss:21.0, fett:1.0, kh:0,
    portionen:[{name:'1 Portion',gramm:100}] },
  { gruppe:'Fisch', name:'Fischstäbchen', alias:['fischstäbchen'],
    kcal:200, eiweiss:11.0, fett:9.0, kh:18.0,
    portionen:[{name:'1 Stäbchen',gramm:30},{name:'3 Stäbchen',gramm:90}] },

  /* ---------- Gemüse ---------- */
  { gruppe:'Gemüse', name:'Tomaten', alias:['tomate'],
    kcal:18, eiweiss:0.9, fett:0.2, kh:2.6,
    portionen:[{name:'1 Tomate',gramm:100},{name:'1 Cocktailtomate',gramm:15},{name:'1 Portion',gramm:150}] },
  { gruppe:'Gemüse', name:'Gurke', alias:['salatgurke','gurken'],
    kcal:12, eiweiss:0.6, fett:0.2, kh:1.8,
    portionen:[{name:'1 Scheibe',gramm:10},{name:'1 halbe Gurke',gramm:200},{name:'1 ganze Gurke',gramm:400}] },
  { gruppe:'Gemüse', name:'Möhren', alias:['karotte','karotten','möhre','mohrrüben','rüebli'],
    kcal:26, eiweiss:0.8, fett:0.2, kh:4.8,
    portionen:[{name:'1 Möhre',gramm:70},{name:'1 Portion',gramm:150}] },
  { gruppe:'Gemüse', name:'Paprika', alias:['paprikaschote','peperoni'],
    kcal:31, eiweiss:1.0, fett:0.3, kh:6.0,
    portionen:[{name:'1 Paprika',gramm:150},{name:'1 halbe Paprika',gramm:75}] },
  { gruppe:'Gemüse', name:'Zwiebel', alias:['zwiebeln'],
    kcal:40, eiweiss:1.1, fett:0.1, kh:8.0,
    portionen:[{name:'1 Zwiebel',gramm:80},{name:'1 halbe Zwiebel',gramm:40}] },
  { gruppe:'Gemüse', name:'Knoblauch', alias:['knoblauchzehe'],
    kcal:141, eiweiss:6.4, fett:0.5, kh:28.0,
    portionen:[{name:'1 Zehe',gramm:4}] },
  { gruppe:'Gemüse', name:'Brokkoli', alias:['broccoli'],
    kcal:34, eiweiss:2.8, fett:0.4, kh:2.7,
    portionen:[{name:'1 Portion',gramm:200},{name:'1 Kopf',gramm:400}] },
  { gruppe:'Gemüse', name:'Blumenkohl', alias:['karfiol'],
    kcal:25, eiweiss:1.9, fett:0.3, kh:2.3,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gemüse', name:'Spinat', alias:['blattspinat','rahmspinat'],
    kcal:23, eiweiss:2.9, fett:0.4, kh:0.6,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gemüse', name:'Zucchini', alias:[],
    kcal:19, eiweiss:1.2, fett:0.3, kh:2.2,
    portionen:[{name:'1 Zucchini',gramm:250}] },
  { gruppe:'Gemüse', name:'Aubergine', alias:['melanzani'],
    kcal:25, eiweiss:1.0, fett:0.2, kh:3.0 },
  { gruppe:'Gemüse', name:'Champignons', alias:['pilze','pilz','champignon'],
    kcal:22, eiweiss:3.1, fett:0.3, kh:0.6,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Champignon',gramm:20}] },
  { gruppe:'Gemüse', name:'Kopfsalat', alias:['salat','eisbergsalat','blattsalat'],
    kcal:14, eiweiss:1.3, fett:0.2, kh:1.1,
    portionen:[{name:'1 Portion',gramm:80},{name:'1 Schüssel',gramm:150}] },
  { gruppe:'Gemüse', name:'Feldsalat', alias:['rapunzel'],
    kcal:14, eiweiss:1.8, fett:0.4, kh:0.7 },
  { gruppe:'Gemüse', name:'Weißkohl', alias:['weißkraut','kohl','sauerkraut'],
    kcal:25, eiweiss:1.3, fett:0.2, kh:4.2 },
  { gruppe:'Gemüse', name:'Rotkohl', alias:['blaukraut','rotkraut'],
    kcal:31, eiweiss:1.5, fett:0.2, kh:4.7 },
  { gruppe:'Gemüse', name:'Rosenkohl', alias:[],
    kcal:43, eiweiss:3.4, fett:0.3, kh:3.3 },
  { gruppe:'Gemüse', name:'Grüne Bohnen', alias:['bohnen','buschbohnen','brechbohnen'],
    kcal:31, eiweiss:1.8, fett:0.1, kh:5.1,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gemüse', name:'Erbsen', alias:['erbse'],
    kcal:81, eiweiss:5.4, fett:0.4, kh:12.3,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Gemüse', name:'Mais', alias:['zuckermais','maiskörner'],
    kcal:86, eiweiss:3.3, fett:1.2, kh:16.0,
    portionen:[{name:'1 Dose',gramm:150},{name:'1 Kolben',gramm:150}] },
  { gruppe:'Gemüse', name:'Lauch', alias:['porree'],
    kcal:29, eiweiss:2.1, fett:0.3, kh:3.3 },
  { gruppe:'Gemüse', name:'Sellerie', alias:['knollensellerie','staudensellerie'],
    kcal:18, eiweiss:1.6, fett:0.3, kh:2.2 },
  { gruppe:'Gemüse', name:'Radieschen', alias:['radieschen'],
    kcal:16, eiweiss:1.1, fett:0.1, kh:2.1,
    portionen:[{name:'1 Radieschen',gramm:10},{name:'1 Bund',gramm:100}] },
  { gruppe:'Gemüse', name:'Rote Bete', alias:['rote rüben','randen'],
    kcal:43, eiweiss:1.5, fett:0.1, kh:8.4 },
  { gruppe:'Gemüse', name:'Kürbis', alias:['hokkaido','butternut'],
    kcal:26, eiweiss:1.0, fett:0.1, kh:4.6 },
  { gruppe:'Gemüse', name:'Spargel', alias:[],
    kcal:20, eiweiss:2.2, fett:0.1, kh:2.0,
    portionen:[{name:'1 Portion',gramm:500},{name:'1 Stange',gramm:25}] },
  { gruppe:'Gemüse', name:'Avocado', alias:[],
    kcal:160, eiweiss:2.0, fett:15.0, kh:1.8,
    portionen:[{name:'1 halbe Avocado',gramm:100},{name:'1 ganze Avocado',gramm:200}] },
  { gruppe:'Gemüse', name:'Oliven', alias:['olive'],
    kcal:145, eiweiss:1.0, fett:15.0, kh:1.0,
    portionen:[{name:'1 Olive',gramm:4},{name:'1 Portion',gramm:30}] },

  /* ---------- Hülsenfrüchte ---------- */
  { gruppe:'Hülsenfrüchte', name:'Linsen, gekocht', alias:['linse','berglinsen','rote linsen'],
    kcal:116, eiweiss:9.0, fett:0.4, kh:17.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Hülsenfrüchte', name:'Kichererbsen, gekocht', alias:['kichererbse'],
    kcal:139, eiweiss:7.5, fett:2.4, kh:18.0,
    portionen:[{name:'1 Dose (abgetropft)',gramm:240}] },
  { gruppe:'Hülsenfrüchte', name:'Kidneybohnen, gekocht', alias:['kidneybohnen','rote bohnen'],
    kcal:110, eiweiss:8.0, fett:0.5, kh:15.0,
    portionen:[{name:'1 Dose (abgetropft)',gramm:240}] },
  { gruppe:'Hülsenfrüchte', name:'Tofu', alias:['sojaquark'],
    kcal:127, eiweiss:14.0, fett:7.0, kh:1.5,
    portionen:[{name:'1 Packung',gramm:200},{name:'1 Portion',gramm:100}] },

  /* ---------- Obst ---------- */
  { gruppe:'Obst', name:'Apfel', alias:['äpfel'],
    kcal:52, eiweiss:0.3, fett:0.2, kh:11.4,
    portionen:[{name:'1 Apfel',gramm:130},{name:'1 großer Apfel',gramm:180}] },
  { gruppe:'Obst', name:'Banane', alias:['bananen'],
    kcal:89, eiweiss:1.1, fett:0.3, kh:20.0,
    portionen:[{name:'1 Banane',gramm:120},{name:'1 große Banane',gramm:150}] },
  { gruppe:'Obst', name:'Birne', alias:['birnen'],
    kcal:57, eiweiss:0.4, fett:0.1, kh:12.4,
    portionen:[{name:'1 Birne',gramm:150}] },
  { gruppe:'Obst', name:'Orange', alias:['apfelsine','orangen'],
    kcal:47, eiweiss:0.9, fett:0.1, kh:9.4,
    portionen:[{name:'1 Orange',gramm:180}] },
  { gruppe:'Obst', name:'Mandarine', alias:['clementine','mandarinen'],
    kcal:53, eiweiss:0.8, fett:0.3, kh:11.5,
    portionen:[{name:'1 Mandarine',gramm:70}] },
  { gruppe:'Obst', name:'Erdbeeren', alias:['erdbeere'],
    kcal:32, eiweiss:0.7, fett:0.3, kh:5.5,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Erdbeere',gramm:12}] },
  { gruppe:'Obst', name:'Heidelbeeren', alias:['blaubeeren'],
    kcal:57, eiweiss:0.7, fett:0.3, kh:12.0,
    portionen:[{name:'1 Portion',gramm:125}] },
  { gruppe:'Obst', name:'Himbeeren', alias:['himbeere'],
    kcal:52, eiweiss:1.2, fett:0.7, kh:5.0,
    portionen:[{name:'1 Portion',gramm:125}] },
  { gruppe:'Obst', name:'Weintrauben', alias:['trauben','weinbeeren'],
    kcal:69, eiweiss:0.7, fett:0.2, kh:15.6,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Traube',gramm:6}] },
  { gruppe:'Obst', name:'Kiwi', alias:[],
    kcal:61, eiweiss:1.1, fett:0.5, kh:11.0,
    portionen:[{name:'1 Kiwi',gramm:75}] },
  { gruppe:'Obst', name:'Ananas', alias:[],
    kcal:50, eiweiss:0.5, fett:0.1, kh:12.0,
    portionen:[{name:'1 Scheibe',gramm:80},{name:'1 Portion',gramm:150}] },
  { gruppe:'Obst', name:'Wassermelone', alias:['melone'],
    kcal:30, eiweiss:0.6, fett:0.2, kh:7.2,
    portionen:[{name:'1 Stück',gramm:200}] },
  { gruppe:'Obst', name:'Honigmelone', alias:['zuckermelone'],
    kcal:36, eiweiss:0.5, fett:0.1, kh:8.3 },
  { gruppe:'Obst', name:'Pfirsich', alias:['nektarine'],
    kcal:39, eiweiss:0.9, fett:0.3, kh:8.4,
    portionen:[{name:'1 Pfirsich',gramm:150}] },
  { gruppe:'Obst', name:'Pflaume', alias:['zwetschge','zwetschgen','pflaumen'],
    kcal:46, eiweiss:0.7, fett:0.3, kh:10.0,
    portionen:[{name:'1 Pflaume',gramm:40}] },
  { gruppe:'Obst', name:'Kirschen', alias:['kirsche'],
    kcal:63, eiweiss:1.1, fett:0.2, kh:13.0,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Obst', name:'Mango', alias:[],
    kcal:60, eiweiss:0.8, fett:0.4, kh:13.0,
    portionen:[{name:'1 halbe Mango',gramm:150}] },
  { gruppe:'Obst', name:'Zitrone', alias:['limette'],
    kcal:29, eiweiss:1.1, fett:0.3, kh:3.2,
    portionen:[{name:'1 Spritzer',gramm:5},{name:'1 Zitrone',gramm:100}] },
  { gruppe:'Obst', name:'Rosinen', alias:['sultaninen'],
    kcal:299, eiweiss:3.1, fett:0.5, kh:70.0,
    portionen:[{name:'1 Handvoll',gramm:30},{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Obst', name:'Datteln', alias:['dattel'],
    kcal:282, eiweiss:2.5, fett:0.4, kh:65.0,
    portionen:[{name:'1 Dattel',gramm:8}] },

  /* ---------- Nüsse und Samen ---------- */
  { gruppe:'Nüsse', name:'Mandeln', alias:['mandel'],
    kcal:579, eiweiss:21.0, fett:50.0, kh:5.5,
    portionen:[{name:'1 Handvoll',gramm:25},{name:'1 Mandel',gramm:1.2}] },
  { gruppe:'Nüsse', name:'Walnüsse', alias:['walnuss'],
    kcal:654, eiweiss:15.0, fett:65.0, kh:7.0,
    portionen:[{name:'1 Handvoll',gramm:25}] },
  { gruppe:'Nüsse', name:'Haselnüsse', alias:['haselnuss'],
    kcal:628, eiweiss:15.0, fett:61.0, kh:7.0,
    portionen:[{name:'1 Handvoll',gramm:25}] },
  { gruppe:'Nüsse', name:'Cashewkerne', alias:['cashew','cashews'],
    kcal:553, eiweiss:18.0, fett:44.0, kh:27.0,
    portionen:[{name:'1 Handvoll',gramm:25}] },
  { gruppe:'Nüsse', name:'Erdnüsse', alias:['erdnuss'],
    kcal:567, eiweiss:26.0, fett:49.0, kh:8.0,
    portionen:[{name:'1 Handvoll',gramm:25}] },
  { gruppe:'Nüsse', name:'Sonnenblumenkerne', alias:[],
    kcal:584, eiweiss:21.0, fett:51.0, kh:12.0,
    portionen:[{name:'1 Esslöffel',gramm:10}] },
  { gruppe:'Nüsse', name:'Erdnussbutter', alias:['erdnussmus'],
    kcal:588, eiweiss:25.0, fett:50.0, kh:12.0,
    portionen:[{name:'1 Esslöffel',gramm:15},{name:'fürs Brot',gramm:20}] },

  /* ---------- Fette und Öle ---------- */
  { gruppe:'Fette', name:'Olivenöl', alias:['öl','olivenoel'], fluessig:true,
    kcal:884, eiweiss:0, fett:100.0, kh:0,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:13}] },
  { gruppe:'Fette', name:'Rapsöl', alias:['pflanzenöl','sonnenblumenöl','bratöl'], fluessig:true,
    kcal:884, eiweiss:0, fett:100.0, kh:0,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:13}] },
  { gruppe:'Fette', name:'Kokosöl', alias:['kokosfett'],
    kcal:884, eiweiss:0, fett:100.0, kh:0,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:13}] },
  { gruppe:'Fette', name:'Mayonnaise', alias:['mayo'],
    kcal:680, eiweiss:1.0, fett:75.0, kh:1.5,
    portionen:[{name:'1 Esslöffel',gramm:15}] },

  /* ---------- Grundzutaten ---------- */
  { gruppe:'Grundzutaten', name:'Weizenmehl Typ 405', alias:['mehl','weizenmehl'],
    kcal:348, eiweiss:10.0, fett:1.0, kh:72.0,
    portionen:[{name:'1 Esslöffel',gramm:10},{name:'100 g',gramm:100}] },
  { gruppe:'Grundzutaten', name:'Vollkornmehl', alias:['weizenvollkornmehl','dinkelmehl'],
    kcal:320, eiweiss:12.0, fett:2.0, kh:60.0 },
  { gruppe:'Grundzutaten', name:'Zucker', alias:['haushaltszucker','kristallzucker'],
    kcal:400, eiweiss:0, fett:0, kh:100.0,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:15},{name:'1 Würfel',gramm:3}] },
  { gruppe:'Grundzutaten', name:'Honig', alias:[],
    kcal:304, eiweiss:0.4, fett:0, kh:75.0,
    portionen:[{name:'1 Teelöffel',gramm:7},{name:'1 Esslöffel',gramm:20}] },
  { gruppe:'Grundzutaten', name:'Marmelade', alias:['konfitüre','gelee','fruchtaufstrich'],
    kcal:250, eiweiss:0.4, fett:0.1, kh:60.0,
    portionen:[{name:'1 Teelöffel',gramm:7},{name:'fürs Brot',gramm:20}] },
  { gruppe:'Grundzutaten', name:'Nuss-Nougat-Creme', alias:['nutella','schokoaufstrich'],
    kcal:539, eiweiss:6.0, fett:31.0, kh:57.0,
    portionen:[{name:'1 Teelöffel',gramm:7},{name:'fürs Brot',gramm:20}] },
  { gruppe:'Grundzutaten', name:'Ketchup', alias:['tomatenketchup'],
    kcal:110, eiweiss:1.2, fett:0.1, kh:24.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Senf', alias:[],
    kcal:80, eiweiss:4.5, fett:4.0, kh:5.0,
    portionen:[{name:'1 Teelöffel',gramm:5}] },
  { gruppe:'Grundzutaten', name:'Tomatenmark', alias:[],
    kcal:82, eiweiss:4.3, fett:0.5, kh:12.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Passierte Tomaten', alias:['tomatensoße','tomatensauce'],
    kcal:32, eiweiss:1.4, fett:0.2, kh:5.5,
    portionen:[{name:'1 Packung',gramm:400}] },
  { gruppe:'Grundzutaten', name:'Gemüsebrühe', alias:['brühe','bouillon'], fluessig:true,
    kcal:4, eiweiss:0.2, fett:0.1, kh:0.4,
    portionen:[{name:'1 Tasse',gramm:200},{name:'1 Teller',gramm:300}] },

  /* ---------- Süßes und Snacks ---------- */
  { gruppe:'Süßes', name:'Vollmilchschokolade', alias:['schokolade','milchschokolade'],
    kcal:535, eiweiss:7.5, fett:30.0, kh:57.0,
    portionen:[{name:'1 Stück',gramm:10},{name:'1 Riegel',gramm:50},{name:'1 Tafel',gramm:100}] },
  { gruppe:'Süßes', name:'Zartbitterschokolade', alias:['dunkle schokolade','bitterschokolade'],
    kcal:530, eiweiss:7.8, fett:38.0, kh:35.0,
    portionen:[{name:'1 Stück',gramm:10},{name:'1 Tafel',gramm:100}] },
  { gruppe:'Süßes', name:'Kekse', alias:['keks','plätzchen','butterkeks','cookie'],
    kcal:460, eiweiss:6.0, fett:18.0, kh:68.0,
    portionen:[{name:'1 Keks',gramm:12},{name:'1 Handvoll',gramm:40}] },
  { gruppe:'Süßes', name:'Kuchen', alias:['rührkuchen','marmorkuchen'],
    kcal:380, eiweiss:5.0, fett:18.0, kh:48.0,
    portionen:[{name:'1 Stück',gramm:80}] },
  { gruppe:'Süßes', name:'Kartoffelchips', alias:['chips'],
    kcal:535, eiweiss:6.0, fett:34.0, kh:50.0,
    portionen:[{name:'1 Handvoll',gramm:25},{name:'1 kleine Tüte',gramm:50},{name:'1 große Tüte',gramm:175}] },
  { gruppe:'Süßes', name:'Gummibärchen', alias:['fruchtgummi','weingummi'],
    kcal:343, eiweiss:6.9, fett:0.1, kh:77.0,
    portionen:[{name:'1 Handvoll',gramm:25},{name:'1 Tüte',gramm:200}] },
  { gruppe:'Süßes', name:'Speiseeis', alias:['eis','eiscreme','vanilleeis'],
    kcal:200, eiweiss:3.5, fett:11.0, kh:22.0,
    portionen:[{name:'1 Kugel',gramm:60},{name:'1 Portion',gramm:120}] },
  { gruppe:'Süßes', name:'Müsliriegel', alias:['energieriegel'],
    kcal:420, eiweiss:6.0, fett:15.0, kh:62.0,
    portionen:[{name:'1 Riegel',gramm:25}] },

  /* ---------- Fertiges und Gerichte ---------- */
  { gruppe:'Gerichte', name:'Pizza Margherita', alias:['pizza'],
    kcal:250, eiweiss:11.0, fett:9.0, kh:31.0,
    portionen:[{name:'1 Stück',gramm:125},{name:'1 ganze Pizza',gramm:400}] },
  { gruppe:'Gerichte', name:'Pizza Salami', alias:[],
    kcal:280, eiweiss:12.0, fett:13.0, kh:29.0,
    portionen:[{name:'1 Stück',gramm:125},{name:'1 ganze Pizza',gramm:400}] },
  { gruppe:'Gerichte', name:'Döner Kebab', alias:['döner','kebap'],
    kcal:215, eiweiss:13.0, fett:11.0, kh:16.0,
    portionen:[{name:'1 Döner',gramm:350}] },
  { gruppe:'Gerichte', name:'Hamburger', alias:['burger','cheeseburger'],
    kcal:250, eiweiss:13.0, fett:12.0, kh:21.0,
    portionen:[{name:'1 Burger',gramm:220}] },
  { gruppe:'Gerichte', name:'Lasagne', alias:[],
    kcal:135, eiweiss:7.0, fett:6.0, kh:12.0,
    portionen:[{name:'1 Portion',gramm:400}] },
  { gruppe:'Gerichte', name:'Gemüsesuppe', alias:['suppe','eintopf'], fluessig:true,
    kcal:40, eiweiss:1.5, fett:1.5, kh:5.0,
    portionen:[{name:'1 Teller',gramm:300},{name:'1 Tasse',gramm:200}] },
  { gruppe:'Gerichte', name:'Rührei', alias:['rühreier'],
    kcal:165, eiweiss:11.0, fett:13.0, kh:1.0,
    portionen:[{name:'aus 2 Eiern',gramm:130},{name:'aus 3 Eiern',gramm:195}] },
  { gruppe:'Gerichte', name:'Pfannkuchen', alias:['eierkuchen','crêpe','palatschinken'],
    kcal:220, eiweiss:7.0, fett:9.0, kh:27.0,
    portionen:[{name:'1 Pfannkuchen',gramm:100}] },

  /* ---------- Getränke ---------- */
  { gruppe:'Getränke', name:'Wasser', alias:['mineralwasser','leitungswasser','sprudel'], fluessig:true,
    kcal:0, eiweiss:0, fett:0, kh:0,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Kaffee, schwarz', alias:['kaffee','filterkaffee'], fluessig:true,
    kcal:2, eiweiss:0.2, fett:0, kh:0.3,
    portionen:[{name:'1 Tasse',gramm:150},{name:'1 große Tasse',gramm:250},{name:'1 Espresso',gramm:30}] },
  { gruppe:'Getränke', name:'Tee, ungesüßt', alias:['tee','schwarztee','kräutertee','grüner tee'], fluessig:true,
    kcal:1, eiweiss:0, fett:0, kh:0.2,
    portionen:[{name:'1 Tasse',gramm:200},{name:'1 Kanne',gramm:1000}] },
  { gruppe:'Getränke', name:'Apfelsaft', alias:['saft','fruchtsaft'], fluessig:true,
    kcal:46, eiweiss:0.1, fett:0.1, kh:11.0,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Orangensaft', alias:['o-saft'], fluessig:true,
    kcal:45, eiweiss:0.7, fett:0.2, kh:10.0,
    portionen:[{name:'1 Glas',gramm:200}] },
  { gruppe:'Getränke', name:'Apfelschorle', alias:['schorle'], fluessig:true,
    kcal:24, eiweiss:0.1, fett:0, kh:5.7,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Cola', alias:['coca cola','limonade','limo'], fluessig:true,
    kcal:42, eiweiss:0, fett:0, kh:10.6,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Dose (0,33 l)',gramm:330},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Cola light', alias:['cola zero','light-limonade'], fluessig:true,
    kcal:0.3, eiweiss:0, fett:0, kh:0,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Dose (0,33 l)',gramm:330}] },
  { gruppe:'Getränke', name:'Bier', alias:['pils','helles','weizenbier'], fluessig:true,
    kcal:43, eiweiss:0.5, fett:0, kh:3.6,
    portionen:[{name:'1 Glas (0,3 l)',gramm:300},{name:'1 Flasche (0,5 l)',gramm:500},{name:'1 Maß',gramm:1000}] },
  { gruppe:'Getränke', name:'Weißwein', alias:['wein','weisswein'], fluessig:true,
    kcal:70, eiweiss:0.1, fett:0, kh:2.6,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 kleines Glas',gramm:125}] },
  { gruppe:'Getränke', name:'Rotwein', alias:[], fluessig:true,
    kcal:74, eiweiss:0.2, fett:0, kh:2.4,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 kleines Glas',gramm:125}] },
  { gruppe:'Getränke', name:'Sekt', alias:['prosecco','champagner'], fluessig:true,
    kcal:80, eiweiss:0.2, fett:0, kh:3.0,
    portionen:[{name:'1 Glas',gramm:100}] }
];

/* Zeichen je Gruppe – erleichtert das Überfliegen der Trefferliste */
const GRUPPEN_ICON = {
  'Beilagen':'🥔', 'Brot':'🍞', 'Frühstück':'🥣', 'Milchprodukte':'🧀', 'Eier':'🥚',
  'Fleisch':'🍖', 'Fisch':'🐟', 'Gemüse':'🥦', 'Hülsenfrüchte':'🫘', 'Obst':'🍎',
  'Nüsse':'🥜', 'Fette':'🫒', 'Grundzutaten':'🥄', 'Süßes':'🍫', 'Gerichte':'🍽️',
  'Getränke':'🥤'
};

/* ---------- Suche ----------
   Sucht in Namen und Aliassen. Ein Treffer am Wortanfang zählt mehr
   als einer mitten im Wort, damit "Kartoffel" nicht hinter
   "Kartoffelsalat" landet.                                        */
function grundnahrungSuche(text){
  const s = text.trim().toLowerCase();
  if (!s) return [];

  const treffer = [];
  GRUNDNAHRUNG.forEach((lm, idx) => {
    const punkte = grundnahrungPunkte(lm, s);
    if (punkte >= 20) treffer.push({ lm, punkte, idx });
  });
  // Bei gleicher Punktzahl entscheidet die Reihenfolge in der Liste oben.
  // Sie ist bewusst gesetzt: „Kartoffeln, gekocht" steht vor „roh", weil
  // das der häufigere Fall ist.
  return treffer
    .sort((a, b) => b.punkte - a.punkte || a.idx - b.idx)
    .slice(0, 12)
    .map(t => grundnahrungAlsLebensmittel(t.lm));
}

function grundnahrungPunkte(lm, s){
  const name = lm.name.toLowerCase();
  const woerter = [name].concat(lm.alias || []);
  let beste = 0;

  for (const wort of woerter){
    const w = wort.toLowerCase();
    let p = 0;
    if (w === s) p = 100;
    else if (w.startsWith(s)) p = 70;
    else if (new RegExp('\\b' + entschaerfen(s)).test(w)) p = 45;  // Wortanfang im Namen
    else if (w.includes(s)) p = 25;
    else if (s.length > 4 && s.startsWith(w)) p = 20;              // "kartoffeln" findet "kartoffel"
    // Alias-Treffer deutlich abwerten: sonst steht bei „Zucker" der
    // Zuckermais vor dem Zucker, weil beide am Wortanfang passen.
    if (p > 0 && wort !== lm.name.toLowerCase()) p -= 20;
    beste = Math.max(beste, p);
  }
  return beste;
}

function entschaerfen(text){
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/* Ins App-Format bringen – dasselbe, das auch offSuche liefert */
function grundnahrungAlsLebensmittel(lm){
  return {
    id: 'basis:' + lm.name,
    quelle: 'basis',
    name: lm.name,
    marke: '',
    bild: '',
    gruppe: lm.gruppe,
    fluessig: !!lm.fluessig,
    kcal100: lm.kcal,
    eiweiss100: lm.eiweiss,
    fett100: lm.fett,
    kh100: lm.kh,
    portionen: lm.portionen || []
  };
}

/* Alle Gruppen mit ihren Lebensmitteln – fürs Stöbern ohne Suchbegriff */
function grundnahrungGruppen(){
  const gruppen = new Map();
  for (const lm of GRUNDNAHRUNG){
    if (!gruppen.has(lm.gruppe)) gruppen.set(lm.gruppe, []);
    gruppen.get(lm.gruppe).push(grundnahrungAlsLebensmittel(lm));
  }
  return gruppen;
}
