/* ============================================================
   WasGegessen? – Grundnahrungsmittel

   Open Food Facts kennt fast nur verpackte Ware mit Barcode. Lose
   Kartoffeln, ein Ei oder ein Stück Butter stehen dort nicht oder nur
   als zufälliges Markenprodukt. Diese Liste schließt die Lücke: die
   Dinge, die man täglich isst, mit verlässlichen Durchschnittswerten.

   Sie steckt fest in der App – die Suche liefert sie sofort, auch
   offline und auch dann, wenn Open Food Facts gerade nicht antwortet.

   Werte je 100 g bzw. 100 ml, nach europäischer Kennzeichnung:
   Kohlenhydrate OHNE Ballaststoffe (so steht es auch auf deutschen
   Packungen). Quelle sind die üblichen Durchschnittswerte für
   unverarbeitete Lebensmittel; Markenware kann abweichen.

   `alias` sind zusätzliche Suchwörter (Plural, Synonyme, Dialekt).
   `portionen` nur dort, wo die Standardportionen aus daten.js nicht
   passen – sonst greift automatisch portionenFuer().
   ============================================================ */

const GRUNDNAHRUNG = [

  /* ---------- Kartoffeln und Beilagen ---------- */
  { gruppe:'Beilagen', name:'Kartoffeln, gekocht', alias:['kartoffel','salzkartoffeln','pellkartoffeln','erdapfel'],
    kcal:80, eiweiss:2.0, fett:0.1, kh:16.5,
    portionen:[{name:'1 mittelgroße Kartoffel',gramm:100},{name:'1 Portion',gramm:200},{name:'1 große Portion',gramm:300}] },
  { gruppe:'Beilagen', name:'Kartoffeln, roh', alias:['kartoffel roh','rohe kartoffeln'],
    kcal:77, eiweiss:2.0, fett:0.1, kh:15.4,
    portionen:[{name:'1 mittelgroße Kartoffel',gramm:100},{name:'1 Portion',gramm:200}] },
  { gruppe:'Beilagen', name:'Bratkartoffeln', alias:['bratkartoffel'],
    kcal:153, eiweiss:2.4, fett:7.5, kh:18.0 },
  { gruppe:'Beilagen', name:'Pommes frites', alias:['pommes','fritten'],
    kcal:290, eiweiss:3.5, fett:14.5, kh:36.0,
    portionen:[{name:'1 kleine Portion',gramm:100},{name:'1 Portion',gramm:150},{name:'1 große Portion',gramm:250}] },
  { gruppe:'Beilagen', name:'Kartoffelpüree', alias:['kartoffelbrei','püree','stampfkartoffeln'],
    kcal:88, eiweiss:2.1, fett:2.5, kh:13.5 },
  { gruppe:'Beilagen', name:'Kartoffelsalat', alias:[],
    kcal:140, eiweiss:1.8, fett:8.0, kh:14.5 },
  { gruppe:'Beilagen', name:'Süßkartoffel, gekocht', alias:['süßkartoffeln','batate'],
    kcal:90, eiweiss:1.6, fett:0.1, kh:20.0 },
  { gruppe:'Beilagen', name:'Reis, gekocht', alias:['reis','weißer reis','basmatireis','langkornreis'],
    kcal:130, eiweiss:2.7, fett:0.3, kh:28.0,
    portionen:[{name:'1 Tasse',gramm:180},{name:'1 Portion',gramm:200},{name:'1 Teller',gramm:300}] },
  { gruppe:'Beilagen', name:'Reis, roh', alias:['reis roh','roher reis'],
    kcal:349, eiweiss:7.0, fett:0.6, kh:77.0,
    portionen:[{name:'1 Portion trocken',gramm:75},{name:'1 große Portion trocken',gramm:100}] },
  { gruppe:'Beilagen', name:'Vollkornreis, gekocht', alias:['naturreis','brauner reis'],
    kcal:111, eiweiss:2.6, fett:0.9, kh:22.0 },
  { gruppe:'Beilagen', name:'Nudeln, gekocht', alias:['nudel','pasta','spaghetti','penne','makkaroni','fusilli'],
    kcal:158, eiweiss:5.8, fett:0.9, kh:31.0,
    portionen:[{name:'1 Portion',gramm:250},{name:'1 kleine Portion',gramm:180},{name:'1 großer Teller',gramm:350}] },
  { gruppe:'Beilagen', name:'Nudeln, roh', alias:['nudeln trocken','pasta roh'],
    kcal:350, eiweiss:12.0, fett:1.5, kh:71.0,
    portionen:[{name:'1 Portion trocken',gramm:100},{name:'1 kleine Portion trocken',gramm:75}] },
  { gruppe:'Beilagen', name:'Vollkornnudeln, gekocht', alias:['vollkornpasta'],
    kcal:124, eiweiss:5.0, fett:0.9, kh:23.0 },
  { gruppe:'Beilagen', name:'Couscous, gekocht', alias:['kuskus'],
    kcal:112, eiweiss:3.8, fett:0.2, kh:23.0 },
  { gruppe:'Beilagen', name:'Bulgur, gekocht', alias:[],
    kcal:83, eiweiss:3.1, fett:0.2, kh:16.0 },
  { gruppe:'Beilagen', name:'Quinoa, gekocht', alias:[],
    kcal:120, eiweiss:4.4, fett:1.9, kh:18.5 },
  { gruppe:'Beilagen', name:'Knödel', alias:['kloß','klöße','knödeln','semmelknödel'],
    kcal:130, eiweiss:3.5, fett:2.0, kh:24.0,
    portionen:[{name:'1 Knödel',gramm:90},{name:'2 Knödel',gramm:180}] },
  { gruppe:'Beilagen', name:'Gnocchi', alias:[],
    kcal:160, eiweiss:4.0, fett:1.0, kh:33.0 },

  /* ---------- Brot und Backwaren ---------- */
  { gruppe:'Brot', name:'Vollkornbrot', alias:['vollkorn brot'],
    kcal:210, eiweiss:7.0, fett:1.5, kh:38.0,
    portionen:[{name:'1 Scheibe',gramm:50},{name:'1 dicke Scheibe',gramm:70}] },
  { gruppe:'Brot', name:'Mischbrot', alias:['graubrot','bauernbrot','brot'],
    kcal:250, eiweiss:7.5, fett:1.2, kh:49.0,
    portionen:[{name:'1 Scheibe',gramm:45},{name:'1 dicke Scheibe',gramm:65}] },
  { gruppe:'Brot', name:'Roggenbrot', alias:['roggenmischbrot'],
    kcal:220, eiweiss:6.5, fett:1.2, kh:42.0,
    portionen:[{name:'1 Scheibe',gramm:50}] },
  { gruppe:'Brot', name:'Weißbrot', alias:['weizenbrot','ciabatta'],
    kcal:265, eiweiss:8.5, fett:3.2, kh:49.0,
    portionen:[{name:'1 Scheibe',gramm:40}] },
  { gruppe:'Brot', name:'Toastbrot', alias:['toast','sandwichtoast'],
    kcal:280, eiweiss:8.0, fett:4.0, kh:50.0,
    portionen:[{name:'1 Scheibe',gramm:25},{name:'2 Scheiben',gramm:50}] },
  { gruppe:'Brot', name:'Brötchen', alias:['semmel','weck','schrippe','rundstück'],
    kcal:280, eiweiss:9.0, fett:2.0, kh:55.0,
    portionen:[{name:'1 Brötchen',gramm:60},{name:'1 halbes Brötchen',gramm:30}] },
  { gruppe:'Brot', name:'Vollkornbrötchen', alias:['körnerbrötchen'],
    kcal:250, eiweiss:9.5, fett:3.5, kh:42.0,
    portionen:[{name:'1 Brötchen',gramm:70}] },
  { gruppe:'Brot', name:'Baguette', alias:['stangenweißbrot'],
    kcal:270, eiweiss:8.5, fett:1.5, kh:54.0,
    portionen:[{name:'1 Stück',gramm:75},{name:'1 halbes Baguette',gramm:125}] },
  { gruppe:'Brot', name:'Pumpernickel', alias:[],
    kcal:190, eiweiss:6.0, fett:1.2, kh:36.0,
    portionen:[{name:'1 Scheibe',gramm:40}] },
  { gruppe:'Brot', name:'Knäckebrot', alias:['knäcke'],
    kcal:340, eiweiss:10.0, fett:1.5, kh:66.0,
    portionen:[{name:'1 Scheibe',gramm:10}] },
  { gruppe:'Brot', name:'Zwieback', alias:[],
    kcal:380, eiweiss:10.0, fett:4.0, kh:74.0,
    portionen:[{name:'1 Stück',gramm:10}] },
  { gruppe:'Brot', name:'Croissant', alias:['hörnchen'],
    kcal:406, eiweiss:8.0, fett:21.0, kh:45.0,
    portionen:[{name:'1 Croissant',gramm:60}] },
  { gruppe:'Brot', name:'Laugenbrezel', alias:['brezel','brezn'],
    kcal:290, eiweiss:9.0, fett:3.0, kh:55.0,
    portionen:[{name:'1 Brezel',gramm:90}] },

  /* ---------- Frühstück ---------- */
  { gruppe:'Frühstück', name:'Haferflocken', alias:['hafer','porridge','haferbrei'],
    kcal:372, eiweiss:13.5, fett:7.0, kh:58.7,
    portionen:[{name:'1 Portion',gramm:50},{name:'1 Schüssel',gramm:80},{name:'1 Esslöffel',gramm:10}] },
  { gruppe:'Frühstück', name:'Müsli', alias:['früchtemüsli','knuspermüsli','granola'],
    kcal:360, eiweiss:9.0, fett:8.0, kh:60.0,
    portionen:[{name:'1 Portion',gramm:50},{name:'1 Schüssel',gramm:80}] },
  { gruppe:'Frühstück', name:'Cornflakes', alias:['frühstücksflocken'],
    kcal:378, eiweiss:7.5, fett:0.9, kh:84.0,
    portionen:[{name:'1 Portion',gramm:40}] },
  { gruppe:'Frühstück', name:'Grieß', alias:['hartweizengrieß','grießbrei'],
    kcal:350, eiweiss:11.0, fett:1.0, kh:73.0 },

  /* ---------- Milch und Milchprodukte ---------- */
  { gruppe:'Milchprodukte', name:'Vollmilch 3,5 %', alias:['milch','vollmilch'], fluessig:true,
    kcal:64, eiweiss:3.4, fett:3.6, kh:4.7,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 Tasse',gramm:150},{name:'1 Schuss',gramm:30}] },
  { gruppe:'Milchprodukte', name:'Fettarme Milch 1,5 %', alias:['fettarme milch','magermilch 1,5'], fluessig:true,
    kcal:47, eiweiss:3.4, fett:1.5, kh:4.9,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 Tasse',gramm:150}] },
  { gruppe:'Milchprodukte', name:'Magermilch 0,3 %', alias:['magermilch','entrahmte milch'], fluessig:true,
    kcal:35, eiweiss:3.5, fett:0.3, kh:4.9 },
  { gruppe:'Milchprodukte', name:'Hafermilch', alias:['haferdrink'], fluessig:true,
    kcal:45, eiweiss:0.8, fett:1.5, kh:6.6 },
  { gruppe:'Milchprodukte', name:'Mandelmilch', alias:['mandeldrink'], fluessig:true,
    kcal:24, eiweiss:0.5, fett:1.6, kh:2.4 },
  { gruppe:'Milchprodukte', name:'Sojamilch', alias:['sojadrink'], fluessig:true,
    kcal:39, eiweiss:3.3, fett:1.8, kh:2.5 },
  { gruppe:'Milchprodukte', name:'Buttermilch', alias:[], fluessig:true,
    kcal:37, eiweiss:3.5, fett:0.5, kh:4.0 },
  { gruppe:'Milchprodukte', name:'Joghurt natur 3,5 %', alias:['joghurt','naturjoghurt'],
    kcal:63, eiweiss:3.5, fett:3.5, kh:4.7,
    portionen:[{name:'1 Becher',gramm:150},{name:'1 großer Becher',gramm:250}] },
  { gruppe:'Milchprodukte', name:'Magerjoghurt 0,1 %', alias:['magerjoghurt','fettarmer joghurt'],
    kcal:38, eiweiss:4.3, fett:0.1, kh:5.0,
    portionen:[{name:'1 Becher',gramm:150}] },
  { gruppe:'Milchprodukte', name:'Griechischer Joghurt 10 %', alias:['griechischer joghurt'],
    kcal:115, eiweiss:5.0, fett:10.0, kh:3.5,
    portionen:[{name:'1 Becher',gramm:150}] },
  { gruppe:'Milchprodukte', name:'Skyr', alias:[],
    kcal:63, eiweiss:11.0, fett:0.2, kh:4.0,
    portionen:[{name:'1 Becher',gramm:150},{name:'1 großer Becher',gramm:450}] },
  { gruppe:'Milchprodukte', name:'Magerquark', alias:['quark','speisequark mager'],
    kcal:67, eiweiss:12.0, fett:0.3, kh:4.1,
    portionen:[{name:'1 Packung',gramm:250},{name:'1 Portion',gramm:125}] },
  { gruppe:'Milchprodukte', name:'Speisequark 20 %', alias:['quark 20'],
    kcal:109, eiweiss:11.5, fett:5.1, kh:3.2 },
  { gruppe:'Milchprodukte', name:'Schlagsahne 30 %', alias:['sahne','schlagobers'],
    kcal:292, eiweiss:2.4, fett:30.0, kh:3.3,
    portionen:[{name:'1 Esslöffel',gramm:15},{name:'1 Becher',gramm:200}] },
  { gruppe:'Milchprodukte', name:'Schmand 24 %', alias:['saure sahne','sauerrahm'],
    kcal:237, eiweiss:2.8, fett:24.0, kh:3.3 },
  { gruppe:'Milchprodukte', name:'Crème fraîche', alias:['creme fraiche'],
    kcal:292, eiweiss:2.4, fett:30.0, kh:3.0 },
  { gruppe:'Milchprodukte', name:'Frischkäse', alias:['doppelrahmfrischkäse','philadelphia'],
    kcal:253, eiweiss:6.0, fett:24.0, kh:3.0,
    portionen:[{name:'1 Esslöffel',gramm:20},{name:'1 Portion fürs Brot',gramm:15}] },
  { gruppe:'Milchprodukte', name:'Hüttenkäse', alias:['körniger frischkäse','cottage cheese'],
    kcal:98, eiweiss:12.0, fett:4.3, kh:3.0,
    portionen:[{name:'1 Becher',gramm:200}] },
  { gruppe:'Milchprodukte', name:'Gouda', alias:['käse','schnittkäse'],
    kcal:356, eiweiss:25.0, fett:28.0, kh:0,
    portionen:[{name:'1 Scheibe',gramm:30},{name:'1 Würfel',gramm:20}] },
  { gruppe:'Milchprodukte', name:'Emmentaler', alias:[],
    kcal:380, eiweiss:28.0, fett:29.0, kh:0,
    portionen:[{name:'1 Scheibe',gramm:30}] },
  { gruppe:'Milchprodukte', name:'Mozzarella', alias:[],
    kcal:254, eiweiss:18.0, fett:20.0, kh:1.0,
    portionen:[{name:'1 Kugel',gramm:125},{name:'1 halbe Kugel',gramm:62}] },
  { gruppe:'Milchprodukte', name:'Feta', alias:['schafskäse','hirtenkäse'],
    kcal:264, eiweiss:14.0, fett:21.0, kh:4.0,
    portionen:[{name:'1 Portion',gramm:50}] },
  { gruppe:'Milchprodukte', name:'Parmesan', alias:['parmigiano','hartkäse'],
    kcal:392, eiweiss:36.0, fett:26.0, kh:0,
    portionen:[{name:'1 Esslöffel gerieben',gramm:8},{name:'1 Portion gerieben',gramm:20}] },
  { gruppe:'Milchprodukte', name:'Camembert', alias:['brie','weichkäse'],
    kcal:300, eiweiss:20.0, fett:24.0, kh:0.5,
    portionen:[{name:'1 Stück',gramm:30}] },
  { gruppe:'Milchprodukte', name:'Butter', alias:['süßrahmbutter','markenbutter'],
    kcal:741, eiweiss:0.7, fett:82.0, kh:0.6,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:15},{name:'fürs Brot',gramm:10},{name:'1 Stück (250 g)',gramm:250}] },
  { gruppe:'Milchprodukte', name:'Margarine', alias:[],
    kcal:720, eiweiss:0.2, fett:80.0, kh:0.4,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:15},{name:'fürs Brot',gramm:10}] },

  /* ---------- Eier ---------- */
  { gruppe:'Eier', name:'Hühnerei', alias:['ei','eier','frühstücksei','spiegelei','rührei gekocht'],
    kcal:143, eiweiss:12.6, fett:9.5, kh:0.7,
    portionen:[{name:'1 Ei (Größe M)',gramm:58},{name:'1 Ei (Größe L)',gramm:68},{name:'1 Ei (Größe S)',gramm:48},{name:'2 Eier (M)',gramm:116}] },
  { gruppe:'Eier', name:'Eiklar', alias:['eiweiß','eiweiss'],
    kcal:52, eiweiss:11.0, fett:0.2, kh:0.7,
    portionen:[{name:'1 Eiklar',gramm:33}] },
  { gruppe:'Eier', name:'Eigelb', alias:['eidotter','dotter'],
    kcal:322, eiweiss:16.0, fett:27.0, kh:3.6,
    portionen:[{name:'1 Eigelb',gramm:18}] },

  /* ---------- Fleisch und Wurst ---------- */
  { gruppe:'Fleisch', name:'Hähnchenbrust', alias:['hühnerbrust','hähnchen','geflügel','pouletbrust'],
    kcal:107, eiweiss:23.0, fett:1.3, kh:0,
    portionen:[{name:'1 Filet',gramm:150},{name:'1 kleines Filet',gramm:100}] },
  { gruppe:'Fleisch', name:'Hähnchenschenkel', alias:['hühnerkeule','hähnchenkeule'],
    kcal:180, eiweiss:19.0, fett:11.0, kh:0,
    portionen:[{name:'1 Schenkel',gramm:130}] },
  { gruppe:'Fleisch', name:'Putenbrust', alias:['pute','truthahn'],
    kcal:105, eiweiss:24.0, fett:1.0, kh:0,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Fleisch', name:'Rinderhackfleisch', alias:['hackfleisch rind','rinderhack','tatar'],
    kcal:150, eiweiss:21.0, fett:7.0, kh:0,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Packung',gramm:500}] },
  { gruppe:'Fleisch', name:'Hackfleisch gemischt', alias:['hackfleisch','gehacktes','mett'],
    kcal:240, eiweiss:18.0, fett:18.0, kh:0,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Packung',gramm:500}] },
  { gruppe:'Fleisch', name:'Schweineschnitzel, roh', alias:['schnitzel','schweinefleisch'],
    kcal:108, eiweiss:22.0, fett:2.0, kh:0,
    portionen:[{name:'1 Schnitzel',gramm:150}] },
  { gruppe:'Fleisch', name:'Schnitzel, paniert', alias:['wiener schnitzel','paniertes schnitzel'],
    kcal:250, eiweiss:17.0, fett:14.0, kh:14.0,
    portionen:[{name:'1 Schnitzel',gramm:180}] },
  { gruppe:'Fleisch', name:'Rindersteak', alias:['steak','rumpsteak','rindfleisch'],
    kcal:150, eiweiss:22.0, fett:6.5, kh:0,
    portionen:[{name:'1 Steak',gramm:200}] },
  { gruppe:'Fleisch', name:'Schweinebauch', alias:['bauchspeck'],
    kcal:350, eiweiss:17.0, fett:31.0, kh:0 },
  { gruppe:'Fleisch', name:'Frühstücksspeck', alias:['speck','bacon'],
    kcal:400, eiweiss:15.0, fett:38.0, kh:0,
    portionen:[{name:'1 Scheibe',gramm:15}] },
  { gruppe:'Fleisch', name:'Kochschinken', alias:['schinken','vorderschinken'],
    kcal:110, eiweiss:20.0, fett:3.0, kh:0.5,
    portionen:[{name:'1 Scheibe',gramm:25}] },
  { gruppe:'Fleisch', name:'Salami', alias:[],
    kcal:380, eiweiss:20.0, fett:33.0, kh:1.0,
    portionen:[{name:'1 Scheibe',gramm:10}] },
  { gruppe:'Fleisch', name:'Bratwurst', alias:['rostbratwurst','grillwurst'],
    kcal:300, eiweiss:13.0, fett:27.0, kh:1.0,
    portionen:[{name:'1 Wurst',gramm:120}] },
  { gruppe:'Fleisch', name:'Wiener Würstchen', alias:['würstchen','frankfurter','bockwurst'],
    kcal:280, eiweiss:12.0, fett:25.0, kh:0.5,
    portionen:[{name:'1 Würstchen',gramm:50},{name:'2 Würstchen',gramm:100}] },
  { gruppe:'Fleisch', name:'Leberwurst', alias:[],
    kcal:320, eiweiss:13.0, fett:29.0, kh:1.5,
    portionen:[{name:'fürs Brot',gramm:20}] },
  { gruppe:'Fleisch', name:'Currywurst', alias:[],
    kcal:290, eiweiss:11.0, fett:24.0, kh:7.0,
    portionen:[{name:'1 Portion',gramm:180}] },

  /* ---------- Fisch ---------- */
  { gruppe:'Fisch', name:'Lachs', alias:['lachsfilet','räucherlachs'],
    kcal:208, eiweiss:20.0, fett:13.0, kh:0,
    portionen:[{name:'1 Filet',gramm:140},{name:'1 Portion',gramm:120}] },
  { gruppe:'Fisch', name:'Thunfisch in Wasser', alias:['thunfisch','tunfisch'],
    kcal:110, eiweiss:25.0, fett:1.0, kh:0,
    portionen:[{name:'1 Dose (abgetropft)',gramm:150}] },
  { gruppe:'Fisch', name:'Forelle', alias:[],
    kcal:119, eiweiss:20.0, fett:4.0, kh:0,
    portionen:[{name:'1 Forelle',gramm:200}] },
  { gruppe:'Fisch', name:'Kabeljau', alias:['dorsch','seelachs'],
    kcal:82, eiweiss:18.0, fett:0.7, kh:0,
    portionen:[{name:'1 Filet',gramm:150}] },
  { gruppe:'Fisch', name:'Hering', alias:['matjes','bismarckhering'],
    kcal:200, eiweiss:18.0, fett:14.0, kh:0 },
  { gruppe:'Fisch', name:'Garnelen', alias:['shrimps','scampi'],
    kcal:99, eiweiss:21.0, fett:1.0, kh:0,
    portionen:[{name:'1 Portion',gramm:100}] },
  { gruppe:'Fisch', name:'Fischstäbchen', alias:['fischstäbchen'],
    kcal:200, eiweiss:11.0, fett:9.0, kh:18.0,
    portionen:[{name:'1 Stäbchen',gramm:30},{name:'3 Stäbchen',gramm:90}] },

  /* ---------- Gemüse ---------- */
  { gruppe:'Gemüse', name:'Tomaten', alias:['tomate'],
    kcal:18, eiweiss:0.9, fett:0.2, kh:2.6,
    portionen:[{name:'1 Tomate',gramm:100},{name:'1 Cocktailtomate',gramm:15},{name:'1 Portion',gramm:150}] },
  { gruppe:'Gemüse', name:'Gurke', alias:['salatgurke','gurken'],
    kcal:12, eiweiss:0.6, fett:0.2, kh:1.8,
    portionen:[{name:'1 Scheibe',gramm:10},{name:'1 halbe Gurke',gramm:200},{name:'1 ganze Gurke',gramm:400}] },
  { gruppe:'Gemüse', name:'Möhren', alias:['karotte','karotten','möhre','mohrrüben','rüebli'],
    kcal:26, eiweiss:0.8, fett:0.2, kh:4.8,
    portionen:[{name:'1 Möhre',gramm:70},{name:'1 Portion',gramm:150}] },
  { gruppe:'Gemüse', name:'Paprika', alias:['paprikaschote','peperoni'],
    kcal:31, eiweiss:1.0, fett:0.3, kh:6.0,
    portionen:[{name:'1 Paprika',gramm:150},{name:'1 halbe Paprika',gramm:75}] },
  { gruppe:'Gemüse', name:'Zwiebel', alias:['zwiebeln'],
    kcal:40, eiweiss:1.1, fett:0.1, kh:8.0,
    portionen:[{name:'1 Zwiebel',gramm:80},{name:'1 halbe Zwiebel',gramm:40}] },
  { gruppe:'Gemüse', name:'Knoblauch', alias:['knoblauchzehe'],
    kcal:141, eiweiss:6.4, fett:0.5, kh:28.0,
    portionen:[{name:'1 Zehe',gramm:4}] },
  { gruppe:'Gemüse', name:'Brokkoli', alias:['broccoli'],
    kcal:34, eiweiss:2.8, fett:0.4, kh:2.7,
    portionen:[{name:'1 Portion',gramm:200},{name:'1 Kopf',gramm:400}] },
  { gruppe:'Gemüse', name:'Blumenkohl', alias:['karfiol'],
    kcal:25, eiweiss:1.9, fett:0.3, kh:2.3,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gemüse', name:'Spinat', alias:['blattspinat','rahmspinat'],
    kcal:23, eiweiss:2.9, fett:0.4, kh:0.6,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gemüse', name:'Zucchini', alias:[],
    kcal:19, eiweiss:1.2, fett:0.3, kh:2.2,
    portionen:[{name:'1 Zucchini',gramm:250}] },
  { gruppe:'Gemüse', name:'Aubergine', alias:['melanzani'],
    kcal:25, eiweiss:1.0, fett:0.2, kh:3.0 },
  { gruppe:'Gemüse', name:'Champignons', alias:['pilze','pilz','champignon'],
    kcal:22, eiweiss:3.1, fett:0.3, kh:0.6,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Champignon',gramm:20}] },
  { gruppe:'Gemüse', name:'Kopfsalat', alias:['salat','eisbergsalat','blattsalat'],
    kcal:14, eiweiss:1.3, fett:0.2, kh:1.1,
    portionen:[{name:'1 Portion',gramm:80},{name:'1 Schüssel',gramm:150}] },
  { gruppe:'Gemüse', name:'Feldsalat', alias:['rapunzel'],
    kcal:14, eiweiss:1.8, fett:0.4, kh:0.7 },
  { gruppe:'Gemüse', name:'Weißkohl', alias:['weißkraut','kohl','sauerkraut'],
    kcal:25, eiweiss:1.3, fett:0.2, kh:4.2 },
  { gruppe:'Gemüse', name:'Rotkohl', alias:['blaukraut','rotkraut'],
    kcal:31, eiweiss:1.5, fett:0.2, kh:4.7 },
  { gruppe:'Gemüse', name:'Rosenkohl', alias:[],
    kcal:43, eiweiss:3.4, fett:0.3, kh:3.3 },
  { gruppe:'Gemüse', name:'Grüne Bohnen', alias:['bohnen','buschbohnen','brechbohnen'],
    kcal:31, eiweiss:1.8, fett:0.1, kh:5.1,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gemüse', name:'Erbsen', alias:['erbse'],
    kcal:81, eiweiss:5.4, fett:0.4, kh:12.3,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Gemüse', name:'Mais', alias:['zuckermais','maiskörner'],
    kcal:86, eiweiss:3.3, fett:1.2, kh:16.0,
    portionen:[{name:'1 Dose',gramm:150},{name:'1 Kolben',gramm:150}] },
  { gruppe:'Gemüse', name:'Lauch', alias:['porree'],
    kcal:29, eiweiss:2.1, fett:0.3, kh:3.3 },
  { gruppe:'Gemüse', name:'Sellerie', alias:['knollensellerie','staudensellerie'],
    kcal:18, eiweiss:1.6, fett:0.3, kh:2.2 },
  { gruppe:'Gemüse', name:'Radieschen', alias:['radieschen'],
    kcal:16, eiweiss:1.1, fett:0.1, kh:2.1,
    portionen:[{name:'1 Radieschen',gramm:10},{name:'1 Bund',gramm:100}] },
  { gruppe:'Gemüse', name:'Rote Bete', alias:['rote rüben','randen'],
    kcal:43, eiweiss:1.5, fett:0.1, kh:8.4 },
  { gruppe:'Gemüse', name:'Kürbis', alias:['hokkaido','butternut'],
    kcal:26, eiweiss:1.0, fett:0.1, kh:4.6 },
  { gruppe:'Gemüse', name:'Spargel', alias:[],
    kcal:20, eiweiss:2.2, fett:0.1, kh:2.0,
    portionen:[{name:'1 Portion',gramm:500},{name:'1 Stange',gramm:25}] },
  { gruppe:'Gemüse', name:'Avocado', alias:[],
    kcal:160, eiweiss:2.0, fett:15.0, kh:1.8,
    portionen:[{name:'1 halbe Avocado',gramm:100},{name:'1 ganze Avocado',gramm:200}] },
  { gruppe:'Gemüse', name:'Oliven', alias:['olive'],
    kcal:145, eiweiss:1.0, fett:15.0, kh:1.0,
    portionen:[{name:'1 Olive',gramm:4},{name:'1 Portion',gramm:30}] },

  /* ---------- Hülsenfrüchte ---------- */
  { gruppe:'Hülsenfrüchte', name:'Linsen, gekocht', alias:['linse','berglinsen','rote linsen'],
    kcal:116, eiweiss:9.0, fett:0.4, kh:17.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Hülsenfrüchte', name:'Kichererbsen, gekocht', alias:['kichererbse'],
    kcal:139, eiweiss:7.5, fett:2.4, kh:18.0,
    portionen:[{name:'1 Dose (abgetropft)',gramm:240}] },
  { gruppe:'Hülsenfrüchte', name:'Kidneybohnen, gekocht', alias:['kidneybohnen','rote bohnen'],
    kcal:110, eiweiss:8.0, fett:0.5, kh:15.0,
    portionen:[{name:'1 Dose (abgetropft)',gramm:240}] },
  { gruppe:'Hülsenfrüchte', name:'Tofu', alias:['sojaquark'],
    kcal:127, eiweiss:14.0, fett:7.0, kh:1.5,
    portionen:[{name:'1 Packung',gramm:200},{name:'1 Portion',gramm:100}] },

  /* ---------- Obst ---------- */
  { gruppe:'Obst', name:'Apfel', alias:['äpfel'],
    kcal:52, eiweiss:0.3, fett:0.2, kh:11.4,
    portionen:[{name:'1 Apfel',gramm:130},{name:'1 großer Apfel',gramm:180}] },
  { gruppe:'Obst', name:'Banane', alias:['bananen'],
    kcal:89, eiweiss:1.1, fett:0.3, kh:20.0,
    portionen:[{name:'1 Banane',gramm:120},{name:'1 große Banane',gramm:150}] },
  { gruppe:'Obst', name:'Birne', alias:['birnen'],
    kcal:57, eiweiss:0.4, fett:0.1, kh:12.4,
    portionen:[{name:'1 Birne',gramm:150}] },
  { gruppe:'Obst', name:'Orange', alias:['apfelsine','orangen'],
    kcal:47, eiweiss:0.9, fett:0.1, kh:9.4,
    portionen:[{name:'1 Orange',gramm:180}] },
  { gruppe:'Obst', name:'Mandarine', alias:['clementine','mandarinen'],
    kcal:53, eiweiss:0.8, fett:0.3, kh:11.5,
    portionen:[{name:'1 Mandarine',gramm:70}] },
  { gruppe:'Obst', name:'Erdbeeren', alias:['erdbeere'],
    kcal:32, eiweiss:0.7, fett:0.3, kh:5.5,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Erdbeere',gramm:12}] },
  { gruppe:'Obst', name:'Heidelbeeren', alias:['blaubeeren'],
    kcal:57, eiweiss:0.7, fett:0.3, kh:12.0,
    portionen:[{name:'1 Portion',gramm:125}] },
  { gruppe:'Obst', name:'Himbeeren', alias:['himbeere'],
    kcal:52, eiweiss:1.2, fett:0.7, kh:5.0,
    portionen:[{name:'1 Portion',gramm:125}] },
  { gruppe:'Obst', name:'Weintrauben', alias:['trauben','weinbeeren'],
    kcal:69, eiweiss:0.7, fett:0.2, kh:15.6,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Traube',gramm:6}] },
  { gruppe:'Obst', name:'Kiwi', alias:[],
    kcal:61, eiweiss:1.1, fett:0.5, kh:11.0,
    portionen:[{name:'1 Kiwi',gramm:75}] },
  { gruppe:'Obst', name:'Ananas', alias:[],
    kcal:50, eiweiss:0.5, fett:0.1, kh:12.0,
    portionen:[{name:'1 Scheibe',gramm:80},{name:'1 Portion',gramm:150}] },
  { gruppe:'Obst', name:'Wassermelone', alias:['melone'],
    kcal:30, eiweiss:0.6, fett:0.2, kh:7.2,
    portionen:[{name:'1 Stück',gramm:200}] },
  { gruppe:'Obst', name:'Honigmelone', alias:['zuckermelone'],
    kcal:36, eiweiss:0.5, fett:0.1, kh:8.3 },
  { gruppe:'Obst', name:'Pfirsich', alias:['nektarine'],
    kcal:39, eiweiss:0.9, fett:0.3, kh:8.4,
    portionen:[{name:'1 Pfirsich',gramm:150}] },
  { gruppe:'Obst', name:'Pflaume', alias:['zwetschge','zwetschgen','pflaumen'],
    kcal:46, eiweiss:0.7, fett:0.3, kh:10.0,
    portionen:[{name:'1 Pflaume',gramm:40}] },
  { gruppe:'Obst', name:'Kirschen', alias:['kirsche'],
    kcal:63, eiweiss:1.1, fett:0.2, kh:13.0,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Obst', name:'Mango', alias:[],
    kcal:60, eiweiss:0.8, fett:0.4, kh:13.0,
    portionen:[{name:'1 halbe Mango',gramm:150}] },
  { gruppe:'Obst', name:'Zitrone', alias:['limette'],
    kcal:29, eiweiss:1.1, fett:0.3, kh:3.2,
    portionen:[{name:'1 Spritzer',gramm:5},{name:'1 Zitrone',gramm:100}] },
  { gruppe:'Obst', name:'Rosinen', alias:['sultaninen'],
    kcal:299, eiweiss:3.1, fett:0.5, kh:70.0,
    portionen:[{name:'1 Handvoll',gramm:30},{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Obst', name:'Datteln', alias:['dattel'],
    kcal:282, eiweiss:2.5, fett:0.4, kh:65.0,
    portionen:[{name:'1 Dattel',gramm:8}] },

  /* ---------- Nüsse und Samen ---------- */
  { gruppe:'Nüsse', name:'Mandeln', alias:['mandel'],
    kcal:579, eiweiss:21.0, fett:50.0, kh:5.5,
    portionen:[{name:'1 Handvoll',gramm:25},{name:'1 Mandel',gramm:1.2}] },
  { gruppe:'Nüsse', name:'Walnüsse', alias:['walnuss'],
    kcal:654, eiweiss:15.0, fett:65.0, kh:7.0,
    portionen:[{name:'1 Handvoll',gramm:25}] },
  { gruppe:'Nüsse', name:'Haselnüsse', alias:['haselnuss'],
    kcal:628, eiweiss:15.0, fett:61.0, kh:7.0,
    portionen:[{name:'1 Handvoll',gramm:25}] },
  { gruppe:'Nüsse', name:'Cashewkerne', alias:['cashew','cashews'],
    kcal:553, eiweiss:18.0, fett:44.0, kh:27.0,
    portionen:[{name:'1 Handvoll',gramm:25}] },
  { gruppe:'Nüsse', name:'Erdnüsse', alias:['erdnuss'],
    kcal:567, eiweiss:26.0, fett:49.0, kh:8.0,
    portionen:[{name:'1 Handvoll',gramm:25}] },
  { gruppe:'Nüsse', name:'Sonnenblumenkerne', alias:[],
    kcal:584, eiweiss:21.0, fett:51.0, kh:12.0,
    portionen:[{name:'1 Esslöffel',gramm:10}] },
  { gruppe:'Nüsse', name:'Erdnussbutter', alias:['erdnussmus'],
    kcal:588, eiweiss:25.0, fett:50.0, kh:12.0,
    portionen:[{name:'1 Esslöffel',gramm:15},{name:'fürs Brot',gramm:20}] },

  /* ---------- Fette und Öle ---------- */
  { gruppe:'Fette', name:'Olivenöl', alias:['öl','olivenoel'], fluessig:true,
    kcal:884, eiweiss:0, fett:100.0, kh:0,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:13}] },
  { gruppe:'Fette', name:'Rapsöl', alias:['pflanzenöl','sonnenblumenöl','bratöl'], fluessig:true,
    kcal:884, eiweiss:0, fett:100.0, kh:0,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:13}] },
  { gruppe:'Fette', name:'Kokosöl', alias:['kokosfett'],
    kcal:884, eiweiss:0, fett:100.0, kh:0,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:13}] },
  { gruppe:'Fette', name:'Mayonnaise', alias:['mayo'],
    kcal:680, eiweiss:1.0, fett:75.0, kh:1.5,
    portionen:[{name:'1 Esslöffel',gramm:15}] },

  /* ---------- Grundzutaten ---------- */
  { gruppe:'Grundzutaten', name:'Weizenmehl Typ 405', alias:['mehl','weizenmehl'],
    kcal:348, eiweiss:10.0, fett:1.0, kh:72.0,
    portionen:[{name:'1 Esslöffel',gramm:10},{name:'100 g',gramm:100}] },
  { gruppe:'Grundzutaten', name:'Vollkornmehl', alias:['weizenvollkornmehl','dinkelmehl'],
    kcal:320, eiweiss:12.0, fett:2.0, kh:60.0 },
  { gruppe:'Grundzutaten', name:'Zucker', alias:['haushaltszucker','kristallzucker'],
    kcal:400, eiweiss:0, fett:0, kh:100.0,
    portionen:[{name:'1 Teelöffel',gramm:5},{name:'1 Esslöffel',gramm:15},{name:'1 Würfel',gramm:3}] },
  { gruppe:'Grundzutaten', name:'Honig', alias:[],
    kcal:304, eiweiss:0.4, fett:0, kh:75.0,
    portionen:[{name:'1 Teelöffel',gramm:7},{name:'1 Esslöffel',gramm:20}] },
  { gruppe:'Grundzutaten', name:'Marmelade', alias:['konfitüre','gelee','fruchtaufstrich'],
    kcal:250, eiweiss:0.4, fett:0.1, kh:60.0,
    portionen:[{name:'1 Teelöffel',gramm:7},{name:'fürs Brot',gramm:20}] },
  { gruppe:'Grundzutaten', name:'Nuss-Nougat-Creme', alias:['nutella','schokoaufstrich'],
    kcal:539, eiweiss:6.0, fett:31.0, kh:57.0,
    portionen:[{name:'1 Teelöffel',gramm:7},{name:'fürs Brot',gramm:20}] },
  { gruppe:'Grundzutaten', name:'Ketchup', alias:['tomatenketchup'],
    kcal:110, eiweiss:1.2, fett:0.1, kh:24.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Senf', alias:[],
    kcal:80, eiweiss:4.5, fett:4.0, kh:5.0,
    portionen:[{name:'1 Teelöffel',gramm:5}] },
  { gruppe:'Grundzutaten', name:'Tomatenmark', alias:[],
    kcal:82, eiweiss:4.3, fett:0.5, kh:12.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Passierte Tomaten', alias:['tomatensoße','tomatensauce'],
    kcal:32, eiweiss:1.4, fett:0.2, kh:5.5,
    portionen:[{name:'1 Packung',gramm:400}] },
  { gruppe:'Grundzutaten', name:'Gemüsebrühe', alias:['brühe','bouillon'], fluessig:true,
    kcal:4, eiweiss:0.2, fett:0.1, kh:0.4,
    portionen:[{name:'1 Tasse',gramm:200},{name:'1 Teller',gramm:300}] },

  /* ---------- Süßes und Snacks ---------- */
  { gruppe:'Süßes', name:'Vollmilchschokolade', alias:['schokolade','milchschokolade'],
    kcal:535, eiweiss:7.5, fett:30.0, kh:57.0,
    portionen:[{name:'1 Stück',gramm:10},{name:'1 Riegel',gramm:50},{name:'1 Tafel',gramm:100}] },
  { gruppe:'Süßes', name:'Zartbitterschokolade', alias:['dunkle schokolade','bitterschokolade'],
    kcal:530, eiweiss:7.8, fett:38.0, kh:35.0,
    portionen:[{name:'1 Stück',gramm:10},{name:'1 Tafel',gramm:100}] },
  { gruppe:'Süßes', name:'Kekse', alias:['keks','plätzchen','butterkeks','cookie'],
    kcal:460, eiweiss:6.0, fett:18.0, kh:68.0,
    portionen:[{name:'1 Keks',gramm:12},{name:'1 Handvoll',gramm:40}] },
  { gruppe:'Süßes', name:'Kuchen', alias:['rührkuchen','marmorkuchen'],
    kcal:380, eiweiss:5.0, fett:18.0, kh:48.0,
    portionen:[{name:'1 Stück',gramm:80}] },
  { gruppe:'Süßes', name:'Kartoffelchips', alias:['chips'],
    kcal:535, eiweiss:6.0, fett:34.0, kh:50.0,
    portionen:[{name:'1 Handvoll',gramm:25},{name:'1 kleine Tüte',gramm:50},{name:'1 große Tüte',gramm:175}] },
  { gruppe:'Süßes', name:'Gummibärchen', alias:['fruchtgummi','weingummi'],
    kcal:343, eiweiss:6.9, fett:0.1, kh:77.0,
    portionen:[{name:'1 Handvoll',gramm:25},{name:'1 Tüte',gramm:200}] },
  { gruppe:'Süßes', name:'Speiseeis', alias:['eis','eiscreme','vanilleeis'],
    kcal:200, eiweiss:3.5, fett:11.0, kh:22.0,
    portionen:[{name:'1 Kugel',gramm:60},{name:'1 Portion',gramm:120}] },
  { gruppe:'Süßes', name:'Müsliriegel', alias:['energieriegel'],
    kcal:420, eiweiss:6.0, fett:15.0, kh:62.0,
    portionen:[{name:'1 Riegel',gramm:25}] },

  /* ---------- Fertiges und Gerichte ---------- */
  { gruppe:'Gerichte', name:'Pizza Margherita', alias:['pizza'],
    kcal:250, eiweiss:11.0, fett:9.0, kh:31.0,
    portionen:[{name:'1 Stück',gramm:125},{name:'1 ganze Pizza',gramm:400}] },
  { gruppe:'Gerichte', name:'Pizza Salami', alias:[],
    kcal:280, eiweiss:12.0, fett:13.0, kh:29.0,
    portionen:[{name:'1 Stück',gramm:125},{name:'1 ganze Pizza',gramm:400}] },
  { gruppe:'Gerichte', name:'Döner Kebab', alias:['döner','kebap'],
    kcal:215, eiweiss:13.0, fett:11.0, kh:16.0,
    portionen:[{name:'1 Döner',gramm:350}] },
  { gruppe:'Gerichte', name:'Hamburger', alias:['burger','cheeseburger'],
    kcal:250, eiweiss:13.0, fett:12.0, kh:21.0,
    portionen:[{name:'1 Burger',gramm:220}] },
  { gruppe:'Gerichte', name:'Lasagne', alias:[],
    kcal:135, eiweiss:7.0, fett:6.0, kh:12.0,
    portionen:[{name:'1 Portion',gramm:400}] },
  { gruppe:'Gerichte', name:'Gemüsesuppe', alias:['suppe','eintopf'], fluessig:true,
    kcal:40, eiweiss:1.5, fett:1.5, kh:5.0,
    portionen:[{name:'1 Teller',gramm:300},{name:'1 Tasse',gramm:200}] },
  { gruppe:'Gerichte', name:'Rührei', alias:['rühreier'],
    kcal:165, eiweiss:11.0, fett:13.0, kh:1.0,
    portionen:[{name:'aus 2 Eiern',gramm:130},{name:'aus 3 Eiern',gramm:195}] },
  { gruppe:'Gerichte', name:'Pfannkuchen', alias:['eierkuchen','crêpe','palatschinken'],
    kcal:220, eiweiss:7.0, fett:9.0, kh:27.0,
    portionen:[{name:'1 Pfannkuchen',gramm:100}] },

  /* ---------- Getränke ---------- */
  { gruppe:'Getränke', name:'Wasser', alias:['mineralwasser','leitungswasser','sprudel'], fluessig:true,
    kcal:0, eiweiss:0, fett:0, kh:0,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Kaffee, schwarz', alias:['kaffee','filterkaffee'], fluessig:true,
    kcal:2, eiweiss:0.2, fett:0, kh:0.3,
    portionen:[{name:'1 Tasse',gramm:150},{name:'1 große Tasse',gramm:250},{name:'1 Espresso',gramm:30}] },
  { gruppe:'Getränke', name:'Tee, ungesüßt', alias:['tee','schwarztee','kräutertee','grüner tee'], fluessig:true,
    kcal:1, eiweiss:0, fett:0, kh:0.2,
    portionen:[{name:'1 Tasse',gramm:200},{name:'1 Kanne',gramm:1000}] },
  { gruppe:'Getränke', name:'Apfelsaft', alias:['saft','fruchtsaft'], fluessig:true,
    kcal:46, eiweiss:0.1, fett:0.1, kh:11.0,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Orangensaft', alias:['o-saft'], fluessig:true,
    kcal:45, eiweiss:0.7, fett:0.2, kh:10.0,
    portionen:[{name:'1 Glas',gramm:200}] },
  { gruppe:'Getränke', name:'Apfelschorle', alias:['schorle'], fluessig:true,
    kcal:24, eiweiss:0.1, fett:0, kh:5.7,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Cola', alias:['coca cola','limonade','limo'], fluessig:true,
    kcal:42, eiweiss:0, fett:0, kh:10.6,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Dose (0,33 l)',gramm:330},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Cola light', alias:['cola zero','light-limonade'], fluessig:true,
    kcal:0.3, eiweiss:0, fett:0, kh:0,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Dose (0,33 l)',gramm:330}] },
  { gruppe:'Getränke', name:'Bier', alias:['pils','helles','weizenbier'], fluessig:true,
    kcal:43, eiweiss:0.5, fett:0, kh:3.6,
    portionen:[{name:'1 Glas (0,3 l)',gramm:300},{name:'1 Flasche (0,5 l)',gramm:500},{name:'1 Maß',gramm:1000}] },
  { gruppe:'Getränke', name:'Weißwein', alias:['wein','weisswein'], fluessig:true,
    kcal:70, eiweiss:0.1, fett:0, kh:2.6,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 kleines Glas',gramm:125}] },
  { gruppe:'Getränke', name:'Rotwein', alias:[], fluessig:true,
    kcal:74, eiweiss:0.2, fett:0, kh:2.4,
    portionen:[{name:'1 Glas',gramm:200},{name:'1 kleines Glas',gramm:125}] },
  { gruppe:'Getränke', name:'Sekt', alias:['prosecco','champagner'], fluessig:true,
    kcal:80, eiweiss:0.2, fett:0, kh:3.0,
    portionen:[{name:'1 Glas',gramm:100}] },

  /* ============================================================
     Fertige Gerichte, Bäckerei und Imbiss

     Zusammengesetztes Essen: die Werte gelten für das Gericht, wie
     man es bekommt. Sie schwanken je nach Rezept stärker als bei
     einzelnen Zutaten – für ein Tagebuch reichen sie trotzdem, und
     die Portion ist meist das, was man wirklich wählt.
     ============================================================ */

  /* ---------- Belegte Brote und Brötchen ---------- */
  { gruppe:'Brot', name:'Belegtes Brötchen mit Käse', alias:['käsebrötchen','belegtes brötchen','käsesemmel'],
    kcal:340, eiweiss:17.0, fett:16.5, kh:34.0,
    portionen:[{name:'1 Brötchen',gramm:100},{name:'1 halbes Brötchen',gramm:50}] },
  { gruppe:'Brot', name:'Belegtes Brötchen mit Schinken', alias:['schinkenbrötchen','schinkensemmel'],
    kcal:265, eiweiss:11.6, fett:8.9, kh:33.7,
    portionen:[{name:'1 Brötchen',gramm:100},{name:'1 halbes Brötchen',gramm:50}] },
  { gruppe:'Brot', name:'Belegtes Brötchen mit Salami', alias:['salamibrötchen','wurstbrötchen'],
    kcal:346, eiweiss:11.0, fett:17.0, kh:35.5,
    portionen:[{name:'1 Brötchen',gramm:95}] },
  { gruppe:'Brot', name:'Mettbrötchen', alias:['mettsemmel','hackepeterbrötchen'],
    kcal:262, eiweiss:13.0, fett:9.3, kh:30.0,
    portionen:[{name:'1 Brötchen',gramm:110}] },
  { gruppe:'Brot', name:'Butterbrot', alias:['butterbrote','brot mit butter'],
    kcal:338, eiweiss:6.2, fett:15.8, kh:40.0,
    portionen:[{name:'1 Scheibe',gramm:55},{name:'2 Scheiben',gramm:110}] },
  { gruppe:'Brot', name:'Käsebrot', alias:['brot mit käse'],
    kcal:335, eiweiss:14.0, fett:17.0, kh:30.0,
    portionen:[{name:'1 Scheibe',gramm:85},{name:'2 Scheiben',gramm:170}] },
  { gruppe:'Brot', name:'Wurstbrot', alias:['brot mit wurst','salamibrot'],
    kcal:338, eiweiss:11.0, fett:18.0, kh:31.0,
    portionen:[{name:'1 Scheibe',gramm:75},{name:'2 Scheiben',gramm:150}] },
  { gruppe:'Brot', name:'Marmeladenbrot', alias:['brot mit marmelade','honigbrot'],
    kcal:315, eiweiss:4.5, fett:11.5, kh:48.0,
    portionen:[{name:'1 Scheibe',gramm:75}] },
  { gruppe:'Brot', name:'Nutellabrot', alias:['schokobrot','brot mit nutella'],
    kcal:338, eiweiss:6.0, fett:13.0, kh:48.0,
    portionen:[{name:'1 Scheibe',gramm:65}] },
  { gruppe:'Brot', name:'Strammer Max', alias:[],
    kcal:280, eiweiss:15.0, fett:16.0, kh:19.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Brot', name:'Sandwich', alias:['belegtes sandwich','clubsandwich'],
    kcal:250, eiweiss:11.0, fett:11.0, kh:26.0,
    portionen:[{name:'1 Sandwich',gramm:150}] },
  { gruppe:'Brot', name:'Toast Hawaii', alias:['überbackener toast'],
    kcal:200, eiweiss:12.0, fett:9.0, kh:18.0,
    portionen:[{name:'1 Scheibe',gramm:120}] },

  /* ---------- Gebäck vom Bäcker ---------- */
  { gruppe:'Brot', name:'Laugenstange', alias:['knusperstange','laugengebäck','laugenstangerl'],
    kcal:290, eiweiss:9.0, fett:4.0, kh:53.0,
    portionen:[{name:'1 Stange',gramm:100},{name:'1 halbe Stange',gramm:50}] },
  { gruppe:'Brot', name:'Käsestange', alias:['blätterteigstange','käseknusperstange'],
    kcal:400, eiweiss:10.0, fett:24.0, kh:34.0,
    portionen:[{name:'1 Stange',gramm:90}] },
  { gruppe:'Brot', name:'Laugenbrötchen', alias:['laugensemmel'],
    kcal:270, eiweiss:9.0, fett:2.5, kh:52.0,
    portionen:[{name:'1 Brötchen',gramm:75}] },
  { gruppe:'Brot', name:'Milchbrötchen', alias:['milchsemmel','rosinenbrötchen'],
    kcal:320, eiweiss:8.0, fett:6.0, kh:57.0,
    portionen:[{name:'1 Brötchen',gramm:60}] },

  /* ---------- Deutsche Alltagsgerichte ---------- */
  { gruppe:'Gerichte', name:'Maultaschen', alias:['maultasche','schwäbische maultaschen'],
    kcal:200, eiweiss:9.0, fett:8.0, kh:22.0,
    portionen:[{name:'1 Maultasche',gramm:75},{name:'1 Portion (3 Stück)',gramm:225},{name:'1 Packung',gramm:400}] },
  { gruppe:'Gerichte', name:'Spätzle', alias:['spätzli','eierspätzle'],
    kcal:170, eiweiss:6.0, fett:3.0, kh:29.0,
    portionen:[{name:'1 Portion',gramm:200},{name:'1 Teller',gramm:300}] },
  { gruppe:'Gerichte', name:'Käsespätzle', alias:['kässpatzen','allgäuer käsespätzle'],
    kcal:250, eiweiss:11.0, fett:13.0, kh:22.0,
    portionen:[{name:'1 Portion',gramm:300}] },
  { gruppe:'Gerichte', name:'Frikadelle', alias:['bulette','fleischpflanzerl','hackbällchen'],
    kcal:280, eiweiss:15.0, fett:21.0, kh:8.0,
    portionen:[{name:'1 Frikadelle',gramm:80},{name:'2 Frikadellen',gramm:160}] },
  { gruppe:'Gerichte', name:'Leberkäse', alias:['fleischkäse','leberkas'],
    kcal:280, eiweiss:13.0, fett:24.0, kh:2.0,
    portionen:[{name:'1 Scheibe',gramm:100}] },
  { gruppe:'Gerichte', name:'Leberkässemmel', alias:['leberkäsbrötchen','fleischkäsesemmel'],
    kcal:280, eiweiss:11.0, fett:16.0, kh:22.0,
    portionen:[{name:'1 Semmel',gramm:160}] },
  { gruppe:'Gerichte', name:'Bratwurst im Brötchen', alias:['rostbratwurst im brötchen','wurstsemmel'],
    kcal:293, eiweiss:11.5, fett:19.0, kh:19.0,
    portionen:[{name:'1 Stück',gramm:180}] },
  { gruppe:'Gerichte', name:'Currywurst mit Pommes', alias:['currywurst pommes'],
    kcal:240, eiweiss:7.0, fett:15.0, kh:19.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Schnitzel mit Pommes', alias:['schnitzel pommes'],
    kcal:260, eiweiss:12.0, fett:14.0, kh:22.0,
    portionen:[{name:'1 Portion',gramm:400}] },
  { gruppe:'Gerichte', name:'Gulasch', alias:['rindergulasch','gulaschtopf'],
    kcal:160, eiweiss:15.0, fett:9.0, kh:4.0,
    portionen:[{name:'1 Portion',gramm:250}] },
  { gruppe:'Gerichte', name:'Rinderroulade', alias:['roulade','rouladen'],
    kcal:180, eiweiss:20.0, fett:10.0, kh:2.0,
    portionen:[{name:'1 Roulade',gramm:180}] },
  { gruppe:'Gerichte', name:'Königsberger Klopse', alias:['klopse'],
    kcal:160, eiweiss:11.0, fett:11.0, kh:5.0,
    portionen:[{name:'1 Portion',gramm:300}] },
  { gruppe:'Gerichte', name:'Kohlrouladen', alias:['krautwickel','kohlroulade'],
    kcal:120, eiweiss:8.0, fett:7.0, kh:6.0,
    portionen:[{name:'1 Roulade',gramm:200}] },
  { gruppe:'Gerichte', name:'Schweinebraten', alias:['krustenbraten','braten'],
    kcal:240, eiweiss:25.0, fett:15.0, kh:1.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Sauerbraten', alias:[],
    kcal:180, eiweiss:22.0, fett:9.0, kh:3.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Kartoffelpuffer', alias:['reibekuchen','reiberdatschi','kartoffelpfannkuchen'],
    kcal:220, eiweiss:4.0, fett:13.0, kh:22.0,
    portionen:[{name:'1 Puffer',gramm:60},{name:'3 Puffer',gramm:180}] },
  { gruppe:'Gerichte', name:'Sauerkraut', alias:['weinsauerkraut'],
    kcal:20, eiweiss:1.5, fett:0.3, kh:2.3,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Rührei mit Speck', alias:['bacon and eggs','speck mit ei'],
    kcal:220, eiweiss:14.0, fett:18.0, kh:1.0,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Gerichte', name:'Omelett', alias:['omelette'],
    kcal:155, eiweiss:11.0, fett:12.0, kh:1.0,
    portionen:[{name:'1 Omelett',gramm:150}] },

  /* ---------- Nudel- und Reisgerichte ---------- */
  { gruppe:'Gerichte', name:'Spaghetti Bolognese', alias:['bolognese','nudeln mit hackfleischsoße'],
    kcal:140, eiweiss:7.0, fett:5.0, kh:16.0,
    portionen:[{name:'1 Portion',gramm:400},{name:'1 kleine Portion',gramm:300}] },
  { gruppe:'Gerichte', name:'Spaghetti Carbonara', alias:['carbonara'],
    kcal:180, eiweiss:8.0, fett:9.0, kh:17.0,
    portionen:[{name:'1 Portion',gramm:400}] },
  { gruppe:'Gerichte', name:'Nudeln mit Tomatensoße', alias:['pasta mit tomatensoße','nudeln mit soße'],
    kcal:120, eiweiss:4.5, fett:2.5, kh:20.0,
    portionen:[{name:'1 Portion',gramm:400}] },
  { gruppe:'Gerichte', name:'Nudelauflauf', alias:['auflauf','überbackene nudeln'],
    kcal:150, eiweiss:8.0, fett:7.0, kh:14.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Chili con Carne', alias:['chili'],
    kcal:120, eiweiss:8.0, fett:5.0, kh:10.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Gebratener Reis', alias:['bratreis','nasi goreng'],
    kcal:165, eiweiss:5.0, fett:6.0, kh:22.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Risotto', alias:[],
    kcal:150, eiweiss:4.0, fett:5.0, kh:22.0,
    portionen:[{name:'1 Portion',gramm:300}] },

  /* ---------- Imbiss und international ---------- */
  { gruppe:'Gerichte', name:'Dürüm', alias:['dürüm döner','yufka'],
    kcal:250, eiweiss:13.0, fett:12.0, kh:22.0,
    portionen:[{name:'1 Dürüm',gramm:400}] },
  { gruppe:'Gerichte', name:'Gyros', alias:['gyros mit tzatziki'],
    kcal:215, eiweiss:17.0, fett:15.0, kh:2.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Falafel', alias:['falafelbällchen'],
    kcal:330, eiweiss:13.0, fett:18.0, kh:28.0,
    portionen:[{name:'1 Kugel',gramm:25},{name:'1 Portion (5 Stück)',gramm:125}] },
  { gruppe:'Gerichte', name:'Wrap', alias:['tortilla wrap','chicken wrap'],
    kcal:220, eiweiss:10.0, fett:9.0, kh:24.0,
    portionen:[{name:'1 Wrap',gramm:200}] },
  { gruppe:'Gerichte', name:'Hot Dog', alias:['hotdog'],
    kcal:250, eiweiss:10.0, fett:14.0, kh:21.0,
    portionen:[{name:'1 Hot Dog',gramm:150}] },
  { gruppe:'Gerichte', name:'Sushi', alias:['maki','nigiri'],
    kcal:145, eiweiss:6.0, fett:2.0, kh:25.0,
    portionen:[{name:'1 Stück',gramm:25},{name:'1 Portion (8 Stück)',gramm:200}] },
  { gruppe:'Gerichte', name:'Frühlingsrolle', alias:['frühlingsrollen'],
    kcal:200, eiweiss:5.0, fett:10.0, kh:22.0,
    portionen:[{name:'1 Rolle',gramm:80}] },
  { gruppe:'Gerichte', name:'Pizzabrötchen', alias:['pizzabrot','knoblauchbrot'],
    kcal:290, eiweiss:9.0, fett:12.0, kh:36.0,
    portionen:[{name:'1 Stück',gramm:40},{name:'1 Portion',gramm:160}] },

  /* ---------- Salate als Mahlzeit ---------- */
  { gruppe:'Gerichte', name:'Salat mit Hähnchenbrust', alias:['hähnchensalat','salatteller'],
    kcal:110, eiweiss:11.0, fett:5.0, kh:4.0,
    portionen:[{name:'1 Portion',gramm:300}] },
  { gruppe:'Gerichte', name:'Griechischer Salat', alias:['bauernsalat'],
    kcal:130, eiweiss:4.0, fett:11.0, kh:4.0,
    portionen:[{name:'1 Portion',gramm:250}] },
  { gruppe:'Gerichte', name:'Caesar Salad', alias:['caesarsalat'],
    kcal:180, eiweiss:9.0, fett:13.0, kh:6.0,
    portionen:[{name:'1 Portion',gramm:250}] },
  { gruppe:'Gerichte', name:'Nudelsalat', alias:[],
    kcal:200, eiweiss:4.0, fett:12.0, kh:19.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Wurstsalat', alias:['fleischsalat'],
    kcal:250, eiweiss:9.0, fett:22.0, kh:3.0,
    portionen:[{name:'1 Portion',gramm:200}] },

  /* ---------- Suppen und Eintöpfe ---------- */
  { gruppe:'Gerichte', name:'Linsensuppe', alias:['linseneintopf'], fluessig:true,
    kcal:90, eiweiss:5.0, fett:2.5, kh:12.0,
    portionen:[{name:'1 Teller',gramm:350},{name:'1 Tasse',gramm:200}] },
  { gruppe:'Gerichte', name:'Erbsensuppe', alias:['erbseneintopf'], fluessig:true,
    kcal:85, eiweiss:5.0, fett:2.5, kh:10.5,
    portionen:[{name:'1 Teller',gramm:350}] },
  { gruppe:'Gerichte', name:'Gulaschsuppe', alias:[], fluessig:true,
    kcal:80, eiweiss:6.0, fett:4.0, kh:5.0,
    portionen:[{name:'1 Teller',gramm:350}] },
  { gruppe:'Gerichte', name:'Tomatensuppe', alias:[], fluessig:true,
    kcal:45, eiweiss:1.2, fett:2.0, kh:5.5,
    portionen:[{name:'1 Teller',gramm:300}] },
  { gruppe:'Gerichte', name:'Hühnersuppe', alias:['hühnerbrühe mit nudeln','nudelsuppe'], fluessig:true,
    kcal:45, eiweiss:3.0, fett:1.5, kh:4.5,
    portionen:[{name:'1 Teller',gramm:300}] },
  { gruppe:'Gerichte', name:'Kürbissuppe', alias:[], fluessig:true,
    kcal:60, eiweiss:1.5, fett:3.5, kh:5.5,
    portionen:[{name:'1 Teller',gramm:300}] },

  /* ---------- Süßes vom Bäcker und Nachtisch ---------- */
  { gruppe:'Süßes', name:'Berliner', alias:['krapfen','pfannkuchen gefüllt','kreppel'],
    kcal:280, eiweiss:5.0, fett:12.0, kh:38.0,
    portionen:[{name:'1 Berliner',gramm:80}] },
  { gruppe:'Süßes', name:'Franzbrötchen', alias:[],
    kcal:400, eiweiss:6.0, fett:19.0, kh:50.0,
    portionen:[{name:'1 Stück',gramm:90}] },
  { gruppe:'Süßes', name:'Donut', alias:['doughnut'],
    kcal:400, eiweiss:5.0, fett:20.0, kh:48.0,
    portionen:[{name:'1 Donut',gramm:60}] },
  { gruppe:'Süßes', name:'Muffin', alias:[],
    kcal:380, eiweiss:5.0, fett:18.0, kh:48.0,
    portionen:[{name:'1 Muffin',gramm:70}] },
  { gruppe:'Süßes', name:'Käsekuchen', alias:['quarkkuchen'],
    kcal:270, eiweiss:7.0, fett:14.0, kh:28.0,
    portionen:[{name:'1 Stück',gramm:120}] },
  { gruppe:'Süßes', name:'Apfelstrudel', alias:['strudel'],
    kcal:240, eiweiss:3.0, fett:11.0, kh:32.0,
    portionen:[{name:'1 Stück',gramm:120}] },
  { gruppe:'Süßes', name:'Streuselkuchen', alias:['blechkuchen'],
    kcal:350, eiweiss:5.0, fett:16.0, kh:46.0,
    portionen:[{name:'1 Stück',gramm:100}] },
  { gruppe:'Süßes', name:'Waffel', alias:['waffeln'],
    kcal:300, eiweiss:6.0, fett:13.0, kh:39.0,
    portionen:[{name:'1 Waffel',gramm:80}] },
  { gruppe:'Süßes', name:'Milchreis', alias:[],
    kcal:130, eiweiss:3.5, fett:3.0, kh:22.0,
    portionen:[{name:'1 Portion',gramm:200},{name:'1 Becher',gramm:200}] },
  { gruppe:'Süßes', name:'Pudding', alias:['schokopudding','vanillepudding','grießbrei'],
    kcal:110, eiweiss:3.0, fett:3.0, kh:18.0,
    portionen:[{name:'1 Becher',gramm:125},{name:'1 Portion',gramm:200}] },
  { gruppe:'Süßes', name:'Fruchtjoghurt', alias:['erdbeerjoghurt','joghurt mit früchten'],
    kcal:95, eiweiss:3.2, fett:2.8, kh:14.0,
    portionen:[{name:'1 Becher',gramm:150},{name:'1 großer Becher',gramm:250}] },
  { gruppe:'Süßes', name:'Obstsalat', alias:['fruchtsalat'],
    kcal:60, eiweiss:0.7, fett:0.2, kh:13.5,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Süßes', name:'Schokoriegel', alias:['mars','snickers','twix','bounty'],
    kcal:480, eiweiss:5.0, fett:22.0, kh:64.0,
    portionen:[{name:'1 Riegel',gramm:50},{name:'1 kleiner Riegel',gramm:25}] },
  { gruppe:'Süßes', name:'Popcorn', alias:['puffmais'],
    kcal:480, eiweiss:7.0, fett:20.0, kh:65.0,
    portionen:[{name:'1 Handvoll',gramm:15},{name:'1 Tüte',gramm:100}] },
  { gruppe:'Süßes', name:'Salzstangen', alias:['brezeln salzig','salzbrezeln'],
    kcal:350, eiweiss:10.0, fett:1.5, kh:73.0,
    portionen:[{name:'1 Handvoll',gramm:25}] },
  { gruppe:'Süßes', name:'Cracker', alias:['salzcracker','tuc'],
    kcal:450, eiweiss:8.0, fett:16.0, kh:66.0,
    portionen:[{name:'1 Cracker',gramm:5},{name:'1 Handvoll',gramm:30}] },
  { gruppe:'Süßes', name:'Reiswaffeln', alias:['reiswaffel'],
    kcal:380, eiweiss:8.0, fett:2.5, kh:80.0,
    portionen:[{name:'1 Waffel',gramm:8},{name:'2 Waffeln',gramm:16}] },
  { gruppe:'Nüsse', name:'Studentenfutter', alias:['nussmischung'],
    kcal:480, eiweiss:14.0, fett:30.0, kh:35.0,
    portionen:[{name:'1 Handvoll',gramm:30}] },

  /* ---------- Aufstriche und Soßen ---------- */
  { gruppe:'Grundzutaten', name:'Hummus', alias:['kichererbsencreme'],
    kcal:240, eiweiss:7.5, fett:17.0, kh:12.0,
    portionen:[{name:'1 Esslöffel',gramm:20},{name:'1 Portion',gramm:50}] },
  { gruppe:'Grundzutaten', name:'Guacamole', alias:['avocadocreme'],
    kcal:160, eiweiss:2.0, fett:15.0, kh:2.5,
    portionen:[{name:'1 Esslöffel',gramm:20}] },
  { gruppe:'Grundzutaten', name:'Pesto', alias:['basilikumpesto'],
    kcal:450, eiweiss:6.0, fett:44.0, kh:5.0,
    portionen:[{name:'1 Esslöffel',gramm:15},{name:'1 Portion',gramm:40}] },
  { gruppe:'Grundzutaten', name:'Salatdressing', alias:['dressing','vinaigrette'],
    kcal:250, eiweiss:1.0, fett:24.0, kh:6.0,
    portionen:[{name:'1 Esslöffel',gramm:15},{name:'1 Portion',gramm:30}] },
  { gruppe:'Grundzutaten', name:'Remoulade', alias:['kräutermayonnaise'],
    kcal:550, eiweiss:1.0, fett:58.0, kh:5.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Sojasoße', alias:['sojasauce'], fluessig:true,
    kcal:60, eiweiss:6.0, fett:0.1, kh:8.0,
    portionen:[{name:'1 Esslöffel',gramm:15},{name:'1 Teelöffel',gramm:5}] },
  { gruppe:'Grundzutaten', name:'Tzatziki', alias:['zaziki','knoblauchsoße'],
    kcal:130, eiweiss:4.0, fett:11.0, kh:3.0,
    portionen:[{name:'1 Esslöffel',gramm:20},{name:'1 Portion',gramm:60}] },

  /* ---------- Kaffeespezialitäten und weitere Getränke ---------- */
  { gruppe:'Getränke', name:'Kaffee mit Milch', alias:['milchkaffee','kaffee milch'], fluessig:true,
    kcal:20, eiweiss:1.1, fett:1.1, kh:1.5,
    portionen:[{name:'1 Tasse',gramm:200},{name:'1 große Tasse',gramm:300}] },
  { gruppe:'Getränke', name:'Cappuccino', alias:[], fluessig:true,
    kcal:45, eiweiss:2.5, fett:2.5, kh:3.3,
    portionen:[{name:'1 Tasse',gramm:150}] },
  { gruppe:'Getränke', name:'Latte Macchiato', alias:['latte','caffè latte'], fluessig:true,
    kcal:50, eiweiss:2.7, fett:2.8, kh:3.7,
    portionen:[{name:'1 Glas',gramm:300}] },
  { gruppe:'Getränke', name:'Eiskaffee', alias:[], fluessig:true,
    kcal:120, eiweiss:2.5, fett:6.0, kh:14.0,
    portionen:[{name:'1 Glas',gramm:250}] },
  { gruppe:'Getränke', name:'Kakao', alias:['trinkschokolade','heiße schokolade','schokomilch'], fluessig:true,
    kcal:80, eiweiss:3.3, fett:3.0, kh:10.0,
    portionen:[{name:'1 Tasse',gramm:250}] },
  { gruppe:'Getränke', name:'Eistee', alias:['ice tea'], fluessig:true,
    kcal:30, eiweiss:0, fett:0, kh:7.5,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Spezi', alias:['cola-mix','mezzo mix'], fluessig:true,
    kcal:45, eiweiss:0, fett:0, kh:11.0,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Energydrink', alias:['energy drink','red bull'], fluessig:true,
    kcal:45, eiweiss:0, fett:0, kh:11.0,
    portionen:[{name:'1 Dose (0,25 l)',gramm:250},{name:'1 Dose (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Smoothie', alias:['fruchtsmoothie'], fluessig:true,
    kcal:55, eiweiss:0.7, fett:0.3, kh:12.0,
    portionen:[{name:'1 Glas',gramm:250},{name:'1 Fläschchen',gramm:250}] },
  { gruppe:'Getränke', name:'Proteinshake', alias:['eiweißshake','protein shake'], fluessig:true,
    kcal:60, eiweiss:8.0, fett:1.2, kh:3.5,
    portionen:[{name:'1 Shake',gramm:400},{name:'1 Glas',gramm:300}] },
  { gruppe:'Getränke', name:'Radler', alias:['alsterwasser'], fluessig:true,
    kcal:38, eiweiss:0.3, fett:0, kh:5.5,
    portionen:[{name:'1 Glas (0,3 l)',gramm:300},{name:'1 Flasche (0,5 l)',gramm:500}] },
  { gruppe:'Getränke', name:'Aperol Spritz', alias:['hugo','spritz'], fluessig:true,
    kcal:90, eiweiss:0, fett:0, kh:9.0,
    portionen:[{name:'1 Glas',gramm:200}] },
  { gruppe:'Getränke', name:'Schnaps', alias:['korn','wodka','whisky','gin','rum'], fluessig:true,
    kcal:230, eiweiss:0, fett:0, kh:0.1,
    portionen:[{name:'1 Schnapsglas',gramm:20},{name:'1 Glas (4 cl)',gramm:40}] },
  { gruppe:'Getränke', name:'Likör', alias:['eierlikör','kräuterlikör'], fluessig:true,
    kcal:300, eiweiss:0.5, fett:1.0, kh:30.0,
    portionen:[{name:'1 Schnapsglas',gramm:20}] },

  /* ============================================================
     Regionale Küche, internationale Klassiker und Imbissvarianten
     ============================================================ */

  /* ---------- Deutsche Regionalgerichte ---------- */
  { gruppe:'Gerichte', name:'Grüne Soße', alias:['grie soß','frankfurter grüne soße','grüne sauce'],
    kcal:120, eiweiss:5.0, fett:9.0, kh:4.0,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Esslöffel',gramm:25}] },
  { gruppe:'Gerichte', name:'Grüne Soße mit Ei und Kartoffeln', alias:['grüne soße gericht'],
    kcal:110, eiweiss:5.5, fett:6.0, kh:9.0,
    portionen:[{name:'1 Portion',gramm:400}] },
  { gruppe:'Gerichte', name:'Handkäs mit Musik', alias:['handkäse','handkäs'],
    kcal:135, eiweiss:22.0, fett:2.0, kh:5.0,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Gerichte', name:'Flammkuchen', alias:['tarte flambée'],
    kcal:230, eiweiss:8.0, fett:12.0, kh:22.0,
    portionen:[{name:'1 Stück',gramm:100},{name:'1 ganzer Flammkuchen',gramm:300}] },
  { gruppe:'Gerichte', name:'Zwiebelkuchen', alias:[],
    kcal:200, eiweiss:6.0, fett:11.0, kh:19.0,
    portionen:[{name:'1 Stück',gramm:150}] },
  { gruppe:'Gerichte', name:'Grünkohl mit Pinkel', alias:['grünkohl'],
    kcal:180, eiweiss:9.0, fett:13.0, kh:6.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Labskaus', alias:[],
    kcal:130, eiweiss:9.0, fett:5.0, kh:12.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Himmel un Ääd', alias:['himmel und erde'],
    kcal:150, eiweiss:5.0, fett:8.0, kh:15.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Saumagen', alias:['pfälzer saumagen'],
    kcal:230, eiweiss:13.0, fett:16.0, kh:8.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Weißwurst', alias:['weisswurst'],
    kcal:260, eiweiss:12.0, fett:23.0, kh:1.0,
    portionen:[{name:'1 Weißwurst',gramm:80},{name:'2 Weißwürste',gramm:160}] },
  { gruppe:'Gerichte', name:'Obatzda', alias:['obazda','obatzter'],
    kcal:290, eiweiss:14.0, fett:24.0, kh:3.0,
    portionen:[{name:'1 Portion',gramm:100}] },
  { gruppe:'Gerichte', name:'Schweinshaxe', alias:['haxe','eisbein','schweinshaxn'],
    kcal:250, eiweiss:22.0, fett:18.0, kh:0,
    portionen:[{name:'1 Haxe',gramm:400}] },
  { gruppe:'Gerichte', name:'Kassler', alias:['kasseler','rippchen'],
    kcal:180, eiweiss:22.0, fett:10.0, kh:0,
    portionen:[{name:'1 Portion',gramm:180}] },
  { gruppe:'Gerichte', name:'Cordon bleu', alias:['cordonbleu'],
    kcal:290, eiweiss:19.0, fett:18.0, kh:13.0,
    portionen:[{name:'1 Stück',gramm:200}] },
  { gruppe:'Gerichte', name:'Zwiebelrostbraten', alias:['rostbraten'],
    kcal:220, eiweiss:20.0, fett:14.0, kh:4.0,
    portionen:[{name:'1 Portion',gramm:250}] },
  { gruppe:'Gerichte', name:'Tafelspitz', alias:[],
    kcal:170, eiweiss:24.0, fett:8.0, kh:0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Hühnerfrikassee', alias:['frikassee'],
    kcal:120, eiweiss:11.0, fett:6.0, kh:6.0,
    portionen:[{name:'1 Portion',gramm:300}] },
  { gruppe:'Gerichte', name:'Hackbraten', alias:['falscher hase','fleischkäse hausgemacht'],
    kcal:240, eiweiss:16.0, fett:17.0, kh:6.0,
    portionen:[{name:'1 Scheibe',gramm:120}] },
  { gruppe:'Gerichte', name:'Senfeier', alias:['eier in senfsoße'],
    kcal:130, eiweiss:8.0, fett:9.0, kh:4.0,
    portionen:[{name:'1 Portion',gramm:300}] },
  { gruppe:'Gerichte', name:'Bauernfrühstück', alias:['bauernomelett'],
    kcal:150, eiweiss:8.0, fett:9.0, kh:9.0,
    portionen:[{name:'1 Portion',gramm:300}] },
  { gruppe:'Gerichte', name:'Kartoffelgratin', alias:['kartoffelauflauf'],
    kcal:150, eiweiss:4.0, fett:9.0, kh:13.0,
    portionen:[{name:'1 Portion',gramm:250}] },
  { gruppe:'Gerichte', name:'Schupfnudeln', alias:['bubespitzle'],
    kcal:190, eiweiss:4.0, fett:8.0, kh:25.0,
    portionen:[{name:'1 Portion',gramm:250}] },
  { gruppe:'Gerichte', name:'Rollmops', alias:['bismarckhering eingelegt'],
    kcal:180, eiweiss:14.0, fett:13.0, kh:2.0,
    portionen:[{name:'1 Rollmops',gramm:75}] },
  { gruppe:'Gerichte', name:'Brathering', alias:['bratheringe'],
    kcal:200, eiweiss:15.0, fett:14.0, kh:3.0,
    portionen:[{name:'1 Stück',gramm:100}] },

  /* ---------- Britisch und amerikanisch ---------- */
  { gruppe:'Gerichte', name:'Fish and Chips', alias:['fish n chips','fish & chips','backfisch mit pommes'],
    kcal:230, eiweiss:11.0, fett:12.0, kh:20.0,
    portionen:[{name:'1 Portion',gramm:400},{name:'1 kleine Portion',gramm:250}] },
  { gruppe:'Gerichte', name:'Backfisch', alias:['fischfilet paniert'],
    kcal:220, eiweiss:14.0, fett:12.0, kh:14.0,
    portionen:[{name:'1 Stück',gramm:150}] },
  { gruppe:'Gerichte', name:'Chicken Nuggets', alias:['nuggets','hähnchennuggets'],
    kcal:270, eiweiss:15.0, fett:16.0, kh:16.0,
    portionen:[{name:'1 Nugget',gramm:18},{name:'6 Stück',gramm:108},{name:'9 Stück',gramm:162}] },
  { gruppe:'Gerichte', name:'Chicken Wings', alias:['hähnchenflügel','wings'],
    kcal:250, eiweiss:20.0, fett:18.0, kh:2.0,
    portionen:[{name:'1 Flügel',gramm:40},{name:'1 Portion (6 Stück)',gramm:240}] },
  { gruppe:'Gerichte', name:'Spare Ribs', alias:['rippchen gegrillt','ribs'],
    kcal:290, eiweiss:18.0, fett:22.0, kh:5.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Pulled Pork', alias:['pulled beef'],
    kcal:200, eiweiss:20.0, fett:11.0, kh:6.0,
    portionen:[{name:'1 Portion',gramm:150},{name:'1 Burger',gramm:250}] },
  { gruppe:'Gerichte', name:'Mac and Cheese', alias:['makkaroni mit käse'],
    kcal:190, eiweiss:8.0, fett:9.0, kh:19.0,
    portionen:[{name:'1 Portion',gramm:300}] },
  { gruppe:'Gerichte', name:'Ofenkartoffel', alias:['baked potato','folienkartoffel'],
    kcal:130, eiweiss:4.0, fett:5.0, kh:17.0,
    portionen:[{name:'1 Kartoffel mit Quark',gramm:350}] },
  { gruppe:'Gerichte', name:'Nachos überbacken', alias:['nachos','tortillachips überbacken'],
    kcal:330, eiweiss:9.0, fett:19.0, kh:31.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Coleslaw', alias:['krautsalat amerikanisch'],
    kcal:150, eiweiss:1.5, fett:12.0, kh:9.0,
    portionen:[{name:'1 Portion',gramm:100}] },
  { gruppe:'Gerichte', name:'Cheeseburger', alias:['käseburger'],
    kcal:270, eiweiss:14.0, fett:14.0, kh:21.0,
    portionen:[{name:'1 Burger',gramm:230},{name:'1 großer Burger',gramm:300}] },
  { gruppe:'Gerichte', name:'Veggieburger', alias:['gemüseburger','veganer burger'],
    kcal:220, eiweiss:9.0, fett:10.0, kh:23.0,
    portionen:[{name:'1 Burger',gramm:220}] },

  /* ---------- Asiatisch ---------- */
  { gruppe:'Gerichte', name:'Ramen', alias:['nudelsuppe japanisch'], fluessig:true,
    kcal:95, eiweiss:5.0, fett:3.5, kh:10.0,
    portionen:[{name:'1 Schale',gramm:500}] },
  { gruppe:'Gerichte', name:'Pho', alias:['phở','vietnamesische nudelsuppe'], fluessig:true,
    kcal:70, eiweiss:5.0, fett:2.0, kh:8.0,
    portionen:[{name:'1 Schale',gramm:500}] },
  { gruppe:'Gerichte', name:'Pad Thai', alias:['padthai'],
    kcal:180, eiweiss:8.0, fett:7.0, kh:21.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Gebratene Nudeln', alias:['bami goreng','chow mein','nudeln asiatisch'],
    kcal:170, eiweiss:6.0, fett:6.0, kh:22.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Hähnchen süß-sauer', alias:['süß sauer','sweet and sour'],
    kcal:150, eiweiss:9.0, fett:5.0, kh:17.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Chop Suey', alias:['gemüsepfanne asiatisch'],
    kcal:95, eiweiss:7.0, fett:4.0, kh:7.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Rotes Thai-Curry', alias:['thai curry','grünes curry','currypfanne'],
    kcal:130, eiweiss:6.0, fett:9.0, kh:6.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Chicken Tikka Masala', alias:['tikka masala','indisches curry'],
    kcal:160, eiweiss:11.0, fett:10.0, kh:6.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Butter Chicken', alias:[],
    kcal:180, eiweiss:12.0, fett:12.0, kh:6.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Naan', alias:['naanbrot','fladenbrot indisch'],
    kcal:300, eiweiss:9.0, fett:7.0, kh:50.0,
    portionen:[{name:'1 Naan',gramm:90}] },
  { gruppe:'Gerichte', name:'Samosa', alias:['samosas'],
    kcal:300, eiweiss:6.0, fett:17.0, kh:31.0,
    portionen:[{name:'1 Samosa',gramm:60}] },
  { gruppe:'Gerichte', name:'Gyoza', alias:['dumplings','teigtaschen asiatisch','dim sum'],
    kcal:200, eiweiss:8.0, fett:8.0, kh:24.0,
    portionen:[{name:'1 Stück',gramm:25},{name:'1 Portion (6 Stück)',gramm:150}] },
  { gruppe:'Gerichte', name:'Misosuppe', alias:['miso suppe'], fluessig:true,
    kcal:35, eiweiss:2.5, fett:1.2, kh:3.0,
    portionen:[{name:'1 Schale',gramm:250}] },
  { gruppe:'Gerichte', name:'Poke Bowl', alias:['pokebowl','sushi bowl'],
    kcal:140, eiweiss:8.0, fett:5.0, kh:15.0,
    portionen:[{name:'1 Schale',gramm:400}] },
  { gruppe:'Gerichte', name:'Edamame', alias:['sojabohnen'],
    kcal:125, eiweiss:11.0, fett:5.0, kh:5.0,
    portionen:[{name:'1 Portion',gramm:100}] },

  /* ---------- Orientalisch, türkisch, griechisch ---------- */
  { gruppe:'Gerichte', name:'Falafelsandwich', alias:['falafel sandwich','falafel im fladenbrot','falafeldürüm'],
    kcal:220, eiweiss:7.0, fett:9.0, kh:27.0,
    portionen:[{name:'1 Sandwich',gramm:300}] },
  { gruppe:'Gerichte', name:'Falafelteller', alias:['falafel teller'],
    kcal:200, eiweiss:8.0, fett:11.0, kh:17.0,
    portionen:[{name:'1 Teller',gramm:400}] },
  { gruppe:'Gerichte', name:'Schawarma', alias:['shawarma'],
    kcal:230, eiweiss:14.0, fett:13.0, kh:15.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Lahmacun', alias:['türkische pizza'],
    kcal:250, eiweiss:11.0, fett:9.0, kh:31.0,
    portionen:[{name:'1 Stück',gramm:180}] },
  { gruppe:'Gerichte', name:'Börek', alias:['boerek','blätterteigtasche'],
    kcal:290, eiweiss:9.0, fett:17.0, kh:26.0,
    portionen:[{name:'1 Stück',gramm:120}] },
  { gruppe:'Gerichte', name:'Pide', alias:['türkisches fladenbrot gefüllt'],
    kcal:260, eiweiss:11.0, fett:10.0, kh:32.0,
    portionen:[{name:'1 Pide',gramm:300}] },
  { gruppe:'Gerichte', name:'Köfte', alias:['kofta','hackfleischbällchen orientalisch'],
    kcal:240, eiweiss:17.0, fett:17.0, kh:4.0,
    portionen:[{name:'1 Köfte',gramm:50},{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Souvlaki', alias:['fleischspieß griechisch'],
    kcal:190, eiweiss:22.0, fett:11.0, kh:1.0,
    portionen:[{name:'1 Spieß',gramm:120}] },
  { gruppe:'Gerichte', name:'Moussaka', alias:['musaka'],
    kcal:150, eiweiss:8.0, fett:10.0, kh:7.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Bifteki', alias:['gefülltes hacksteak'],
    kcal:250, eiweiss:18.0, fett:18.0, kh:4.0,
    portionen:[{name:'1 Stück',gramm:200}] },
  { gruppe:'Gerichte', name:'Halloumi gebraten', alias:['halloumi','grillkäse'],
    kcal:330, eiweiss:22.0, fett:26.0, kh:2.0,
    portionen:[{name:'1 Portion',gramm:100}] },
  { gruppe:'Gerichte', name:'Dolma', alias:['gefüllte weinblätter'],
    kcal:180, eiweiss:3.0, fett:11.0, kh:17.0,
    portionen:[{name:'1 Stück',gramm:30}] },
  { gruppe:'Gerichte', name:'Hummusteller', alias:['mezze','mezzeteller'],
    kcal:230, eiweiss:8.0, fett:15.0, kh:15.0,
    portionen:[{name:'1 Teller',gramm:300}] },

  /* ---------- Italienisch ---------- */
  { gruppe:'Gerichte', name:'Pasta mit Pesto', alias:['nudeln mit pesto'],
    kcal:200, eiweiss:6.0, fett:10.0, kh:21.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Calzone', alias:['gefüllte pizza'],
    kcal:250, eiweiss:12.0, fett:10.0, kh:28.0,
    portionen:[{name:'1 Calzone',gramm:350}] },
  { gruppe:'Gerichte', name:'Bruschetta', alias:['crostini'],
    kcal:190, eiweiss:5.0, fett:7.0, kh:26.0,
    portionen:[{name:'1 Scheibe',gramm:50}] },
  { gruppe:'Gerichte', name:'Focaccia', alias:[],
    kcal:290, eiweiss:7.0, fett:12.0, kh:38.0,
    portionen:[{name:'1 Stück',gramm:100}] },
  { gruppe:'Gerichte', name:'Antipasti', alias:['eingelegtes gemüse'],
    kcal:130, eiweiss:2.0, fett:11.0, kh:6.0,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Gerichte', name:'Caprese', alias:['tomate mozzarella'],
    kcal:160, eiweiss:9.0, fett:12.0, kh:3.0,
    portionen:[{name:'1 Portion',gramm:200}] },
  { gruppe:'Gerichte', name:'Minestrone', alias:['gemüsesuppe italienisch'], fluessig:true,
    kcal:55, eiweiss:2.5, fett:2.0, kh:6.5,
    portionen:[{name:'1 Teller',gramm:350}] },
  { gruppe:'Gerichte', name:'Vitello tonnato', alias:[],
    kcal:210, eiweiss:18.0, fett:14.0, kh:3.0,
    portionen:[{name:'1 Portion',gramm:150}] },

  /* ---------- Spanisch und mexikanisch ---------- */
  { gruppe:'Gerichte', name:'Paella', alias:[],
    kcal:150, eiweiss:9.0, fett:4.0, kh:19.0,
    portionen:[{name:'1 Portion',gramm:400}] },
  { gruppe:'Gerichte', name:'Tortilla española', alias:['tortilla','kartoffelomelett'],
    kcal:180, eiweiss:7.0, fett:12.0, kh:11.0,
    portionen:[{name:'1 Stück',gramm:150}] },
  { gruppe:'Gerichte', name:'Burrito', alias:[],
    kcal:210, eiweiss:9.0, fett:8.0, kh:25.0,
    portionen:[{name:'1 Burrito',gramm:300}] },
  { gruppe:'Gerichte', name:'Taco', alias:['tacos'],
    kcal:220, eiweiss:10.0, fett:11.0, kh:20.0,
    portionen:[{name:'1 Taco',gramm:90}] },
  { gruppe:'Gerichte', name:'Quesadilla', alias:[],
    kcal:290, eiweiss:13.0, fett:16.0, kh:24.0,
    portionen:[{name:'1 Stück',gramm:150}] },
  { gruppe:'Gerichte', name:'Enchiladas', alias:['enchilada'],
    kcal:190, eiweiss:9.0, fett:9.0, kh:18.0,
    portionen:[{name:'1 Portion',gramm:300}] },

  /* ---------- Belegte Brote, Sandwiches, Bowls ---------- */
  { gruppe:'Brot', name:'Thunfischsandwich', alias:['thunfisch sandwich'],
    kcal:230, eiweiss:13.0, fett:9.0, kh:24.0,
    portionen:[{name:'1 Sandwich',gramm:180}] },
  { gruppe:'Brot', name:'Hähnchensandwich', alias:['chicken sandwich','hühnchensandwich'],
    kcal:240, eiweiss:15.0, fett:9.0, kh:24.0,
    portionen:[{name:'1 Sandwich',gramm:200}] },
  { gruppe:'Brot', name:'Eiersandwich', alias:['ei sandwich','eierbrötchen'],
    kcal:250, eiweiss:11.0, fett:14.0, kh:20.0,
    portionen:[{name:'1 Sandwich',gramm:150}] },
  { gruppe:'Brot', name:'Bagel mit Frischkäse', alias:['bagel','bagel mit lachs'],
    kcal:270, eiweiss:11.0, fett:9.0, kh:36.0,
    portionen:[{name:'1 Bagel',gramm:150}] },
  { gruppe:'Brot', name:'Panini', alias:['gepresstes sandwich'],
    kcal:270, eiweiss:13.0, fett:12.0, kh:27.0,
    portionen:[{name:'1 Panini',gramm:200}] },
  { gruppe:'Brot', name:'Croque Monsieur', alias:['croque','überbackenes schinkensandwich'],
    kcal:290, eiweiss:15.0, fett:17.0, kh:20.0,
    portionen:[{name:'1 Stück',gramm:180}] },
  { gruppe:'Brot', name:'Avocadobrot', alias:['avocado toast','avocadotoast'],
    kcal:220, eiweiss:6.0, fett:13.0, kh:19.0,
    portionen:[{name:'1 Scheibe',gramm:120}] },
  { gruppe:'Brot', name:'Lachsbrot', alias:['brot mit lachs','graved lachs brot'],
    kcal:250, eiweiss:14.0, fett:13.0, kh:19.0,
    portionen:[{name:'1 Scheibe',gramm:85}] },

  /* ---------- Frühstück ---------- */
  { gruppe:'Frühstück', name:'Porridge', alias:['haferbrei gekocht','overnight oats'],
    kcal:95, eiweiss:3.5, fett:2.0, kh:15.0,
    portionen:[{name:'1 Schale',gramm:350}] },
  { gruppe:'Frühstück', name:'Bircher Müsli', alias:['birchermüesli'],
    kcal:150, eiweiss:4.0, fett:4.0, kh:23.0,
    portionen:[{name:'1 Schale',gramm:250}] },
  { gruppe:'Frühstück', name:'Joghurt mit Müsli', alias:['müsli mit joghurt'],
    kcal:140, eiweiss:5.0, fett:4.5, kh:19.0,
    portionen:[{name:'1 Schale',gramm:250}] },
  { gruppe:'Frühstück', name:'Pancakes', alias:['amerikanische pfannkuchen'],
    kcal:240, eiweiss:6.0, fett:9.0, kh:33.0,
    portionen:[{name:'1 Pancake',gramm:50},{name:'3 Pancakes',gramm:150}] },
  { gruppe:'Frühstück', name:'Arme Ritter', alias:['french toast','semmelschmarrn'],
    kcal:250, eiweiss:8.0, fett:11.0, kh:30.0,
    portionen:[{name:'1 Scheibe',gramm:80}] },
  { gruppe:'Frühstück', name:'Smoothie Bowl', alias:['açai bowl','acai bowl'],
    kcal:110, eiweiss:3.0, fett:3.0, kh:17.0,
    portionen:[{name:'1 Schale',gramm:300}] },

  /* ---------- Süßes und Gebäck ---------- */
  { gruppe:'Süßes', name:'Tiramisu', alias:[],
    kcal:270, eiweiss:5.0, fett:16.0, kh:26.0,
    portionen:[{name:'1 Portion',gramm:120}] },
  { gruppe:'Süßes', name:'Panna cotta', alias:[],
    kcal:250, eiweiss:3.0, fett:18.0, kh:20.0,
    portionen:[{name:'1 Portion',gramm:120}] },
  { gruppe:'Süßes', name:'Baklava', alias:[],
    kcal:430, eiweiss:6.0, fett:23.0, kh:50.0,
    portionen:[{name:'1 Stück',gramm:40}] },
  { gruppe:'Süßes', name:'Kaiserschmarrn', alias:['kaiserschmarren'],
    kcal:250, eiweiss:7.0, fett:10.0, kh:32.0,
    portionen:[{name:'1 Portion',gramm:250}] },
  { gruppe:'Süßes', name:'Germknödel', alias:['dampfnudel'],
    kcal:230, eiweiss:6.0, fett:5.0, kh:39.0,
    portionen:[{name:'1 Knödel',gramm:200}] },
  { gruppe:'Süßes', name:'Brownie', alias:['schokokuchen'],
    kcal:430, eiweiss:5.0, fett:23.0, kh:50.0,
    portionen:[{name:'1 Stück',gramm:60}] },
  { gruppe:'Süßes', name:'Zimtschnecke', alias:['franzbrötchen süß','zimtrolle'],
    kcal:360, eiweiss:6.0, fett:14.0, kh:52.0,
    portionen:[{name:'1 Stück',gramm:90}] },
  { gruppe:'Süßes', name:'Nussecke', alias:[],
    kcal:460, eiweiss:7.0, fett:28.0, kh:44.0,
    portionen:[{name:'1 Stück',gramm:70}] },
  { gruppe:'Süßes', name:'Amerikaner', alias:['ausstecher'],
    kcal:360, eiweiss:5.0, fett:11.0, kh:59.0,
    portionen:[{name:'1 Stück',gramm:70}] },
  { gruppe:'Süßes', name:'Bienenstich', alias:[],
    kcal:330, eiweiss:5.0, fett:18.0, kh:36.0,
    portionen:[{name:'1 Stück',gramm:110}] },
  { gruppe:'Süßes', name:'Schwarzwälder Kirschtorte', alias:['sahnetorte','torte'],
    kcal:290, eiweiss:4.0, fett:18.0, kh:28.0,
    portionen:[{name:'1 Stück',gramm:120}] },
  { gruppe:'Süßes', name:'Softeis', alias:['eis im hörnchen','frozen yogurt'],
    kcal:180, eiweiss:4.0, fett:7.0, kh:25.0,
    portionen:[{name:'1 Hörnchen',gramm:120}] },
  { gruppe:'Süßes', name:'Eis am Stiel', alias:['wassereis','magnum'],
    kcal:250, eiweiss:3.0, fett:15.0, kh:26.0,
    portionen:[{name:'1 Stück',gramm:80}] },
  { gruppe:'Süßes', name:'Quarkspeise', alias:['quark mit früchten','skyr mit früchten'],
    kcal:100, eiweiss:8.0, fett:2.0, kh:12.0,
    portionen:[{name:'1 Portion',gramm:200}] },

  /* ---------- Soßen und Dips ---------- */
  { gruppe:'Grundzutaten', name:'Bratensoße', alias:['soße','sauce','jus'], fluessig:true,
    kcal:50, eiweiss:1.5, fett:3.0, kh:4.0,
    portionen:[{name:'1 Schöpfkelle',gramm:60},{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Rahmsoße', alias:['sahnesoße','jägersoße','champignonsoße'], fluessig:true,
    kcal:110, eiweiss:2.0, fett:9.0, kh:5.0,
    portionen:[{name:'1 Schöpfkelle',gramm:60}] },
  { gruppe:'Grundzutaten', name:'Currysoße', alias:['currysauce'], fluessig:true,
    kcal:110, eiweiss:1.0, fett:3.0, kh:19.0,
    portionen:[{name:'1 Portion',gramm:50}] },
  { gruppe:'Grundzutaten', name:'BBQ-Soße', alias:['barbecuesoße','grillsoße'], fluessig:true,
    kcal:150, eiweiss:1.0, fett:0.5, kh:35.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Sweet-Chili-Soße', alias:['chilisoße','sweet chili'], fluessig:true,
    kcal:230, eiweiss:0.5, fett:0.2, kh:56.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Aioli', alias:['knoblauchmayonnaise'],
    kcal:600, eiweiss:1.5, fett:64.0, kh:3.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Cocktailsoße', alias:['cocktailsauce'],
    kcal:400, eiweiss:1.0, fett:38.0, kh:13.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },
  { gruppe:'Grundzutaten', name:'Balsamicoessig', alias:['essig','balsamico'], fluessig:true,
    kcal:90, eiweiss:0.5, fett:0, kh:17.0,
    portionen:[{name:'1 Esslöffel',gramm:15}] },

  /* ---------- Vegetarisch und vegan ---------- */
  { gruppe:'Gerichte', name:'Gemüsepfanne', alias:['gemüse gebraten','wokgemüse'],
    kcal:80, eiweiss:3.0, fett:4.0, kh:7.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Ratatouille', alias:['schmorgemüse'],
    kcal:70, eiweiss:1.5, fett:4.5, kh:5.5,
    portionen:[{name:'1 Portion',gramm:300}] },
  { gruppe:'Gerichte', name:'Linsenbolognese', alias:['vegane bolognese'],
    kcal:95, eiweiss:5.0, fett:3.0, kh:11.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Gerichte', name:'Gemüseauflauf', alias:['überbackenes gemüse'],
    kcal:110, eiweiss:6.0, fett:6.0, kh:8.0,
    portionen:[{name:'1 Portion',gramm:350}] },
  { gruppe:'Hülsenfrüchte', name:'Seitan', alias:['weizenfleisch'],
    kcal:140, eiweiss:25.0, fett:2.0, kh:6.0,
    portionen:[{name:'1 Portion',gramm:100}] },
  { gruppe:'Hülsenfrüchte', name:'Sojaschnetzel', alias:['sojagranulat','sojafleisch'],
    kcal:120, eiweiss:17.0, fett:1.0, kh:8.0,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Hülsenfrüchte', name:'Weiße Bohnen', alias:['baked beans','cannellini'],
    kcal:105, eiweiss:7.0, fett:0.5, kh:15.0,
    portionen:[{name:'1 Dose (abgetropft)',gramm:240}] },
  { gruppe:'Hülsenfrüchte', name:'Erbsenpüree', alias:['erbsenmus'],
    kcal:90, eiweiss:6.0, fett:1.5, kh:12.0,
    portionen:[{name:'1 Portion',gramm:200}] },

  /* ---------- Fisch und Meeresfrüchte ---------- */
  { gruppe:'Fisch', name:'Makrele', alias:['räuchermakrele'],
    kcal:250, eiweiss:19.0, fett:19.0, kh:0,
    portionen:[{name:'1 Filet',gramm:150}] },
  { gruppe:'Fisch', name:'Pangasius', alias:['viktoriabarsch','tilapia'],
    kcal:90, eiweiss:15.0, fett:3.0, kh:0,
    portionen:[{name:'1 Filet',gramm:150}] },
  { gruppe:'Fisch', name:'Scholle', alias:['flunder'],
    kcal:85, eiweiss:17.0, fett:1.5, kh:0,
    portionen:[{name:'1 Filet',gramm:160}] },
  { gruppe:'Fisch', name:'Muscheln', alias:['miesmuscheln'],
    kcal:85, eiweiss:12.0, fett:2.0, kh:4.0,
    portionen:[{name:'1 Portion',gramm:300}] },
  { gruppe:'Fisch', name:'Calamari', alias:['tintenfischringe'],
    kcal:200, eiweiss:13.0, fett:10.0, kh:15.0,
    portionen:[{name:'1 Portion',gramm:150}] },
  { gruppe:'Fisch', name:'Sardinen', alias:['ölsardinen'],
    kcal:220, eiweiss:21.0, fett:15.0, kh:0,
    portionen:[{name:'1 Dose',gramm:90}] },

  /* ---------- Fleisch ---------- */
  { gruppe:'Fleisch', name:'Brathähnchen', alias:['grillhähnchen','hähnchen vom grill'],
    kcal:200, eiweiss:22.0, fett:12.0, kh:0,
    portionen:[{name:'1 halbes Hähnchen',gramm:350}] },
  { gruppe:'Fleisch', name:'Entenbrust', alias:['ente'],
    kcal:200, eiweiss:19.0, fett:14.0, kh:0,
    portionen:[{name:'1 Portion',gramm:180}] },
  { gruppe:'Fleisch', name:'Gänsebraten', alias:['gans'],
    kcal:290, eiweiss:22.0, fett:22.0, kh:0,
    portionen:[{name:'1 Portion',gramm:250}] },
  { gruppe:'Fleisch', name:'Lammkotelett', alias:['lamm','lammfleisch'],
    kcal:230, eiweiss:20.0, fett:17.0, kh:0,
    portionen:[{name:'1 Kotelett',gramm:120}] },
  { gruppe:'Fleisch', name:'Fleischwurst', alias:['lyoner','gelbwurst'],
    kcal:290, eiweiss:12.0, fett:26.0, kh:1.0,
    portionen:[{name:'1 Scheibe',gramm:25}] },
  { gruppe:'Fleisch', name:'Mortadella', alias:[],
    kcal:310, eiweiss:15.0, fett:27.0, kh:1.0,
    portionen:[{name:'1 Scheibe',gramm:20}] },
  { gruppe:'Fleisch', name:'Cabanossi', alias:['mini salami','snackwurst'],
    kcal:400, eiweiss:20.0, fett:35.0, kh:1.0,
    portionen:[{name:'1 Stück',gramm:35}] },
  { gruppe:'Fleisch', name:'Rohschinken', alias:['serranoschinken','parmaschinken','schwarzwälder schinken'],
    kcal:240, eiweiss:28.0, fett:14.0, kh:0,
    portionen:[{name:'1 Scheibe',gramm:15}] }
];

/* Zeichen je Gruppe – erleichtert das Überfliegen der Trefferliste */
const GRUPPEN_ICON = {
  'Beilagen':'🥔', 'Brot':'🍞', 'Frühstück':'🥣', 'Milchprodukte':'🧀', 'Eier':'🥚',
  'Fleisch':'🍖', 'Fisch':'🐟', 'Gemüse':'🥦', 'Hülsenfrüchte':'🫘', 'Obst':'🍎',
  'Nüsse':'🥜', 'Fette':'🫒', 'Grundzutaten':'🥄', 'Süßes':'🍫', 'Gerichte':'🍽️',
  'Getränke':'🥤'
};

/* ---------- Suche ----------
   Sucht in Namen und Aliassen. Ein Treffer am Wortanfang zählt mehr
   als einer mitten im Wort, damit "Kartoffel" nicht hinter
   "Kartoffelsalat" landet.                                        */
function grundnahrungSuche(text){
  const s = text.trim().toLowerCase();
  if (!s) return [];

  const treffer = [];
  GRUNDNAHRUNG.forEach((lm, idx) => {
    const punkte = grundnahrungPunkte(lm, s);
    if (punkte >= 20) treffer.push({ lm, punkte, idx });
  });
  // Bei gleicher Punktzahl entscheidet die Reihenfolge in der Liste oben.
  // Sie ist bewusst gesetzt: „Kartoffeln, gekocht" steht vor „roh", weil
  // das der häufigere Fall ist.
  return treffer
    .sort((a, b) => b.punkte - a.punkte || a.idx - b.idx)
    .slice(0, 12)
    .map(t => grundnahrungAlsLebensmittel(t.lm));
}

function grundnahrungPunkte(lm, s){
  const name = lm.name.toLowerCase();
  const woerter = [name].concat(lm.alias || []);
  let beste = 0;

  for (const wort of woerter){
    const w = wort.toLowerCase();
    let p = 0;
    if (w === s) p = 100;
    else if (w.startsWith(s)) p = 70;
    else if (new RegExp('\\b' + entschaerfen(s)).test(w)) p = 45;  // Wortanfang im Namen
    else if (w.includes(s)) p = 25;
    else if (s.length > 4 && s.startsWith(w)) p = 20;              // "kartoffeln" findet "kartoffel"
    // Alias-Treffer deutlich abwerten: sonst steht bei „Zucker" der
    // Zuckermais vor dem Zucker, weil beide am Wortanfang passen.
    if (p > 0 && wort !== lm.name.toLowerCase()) p -= 20;
    beste = Math.max(beste, p);
  }
  return beste;
}

function entschaerfen(text){
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/* Ins App-Format bringen – dasselbe, das auch offSuche liefert */
function grundnahrungAlsLebensmittel(lm){
  return {
    id: 'basis:' + lm.name,
    quelle: 'basis',
    name: lm.name,
    marke: '',
    bild: '',
    gruppe: lm.gruppe,
    fluessig: !!lm.fluessig,
    kcal100: lm.kcal,
    eiweiss100: lm.eiweiss,
    fett100: lm.fett,
    kh100: lm.kh,
    portionen: lm.portionen || []
  };
}

/* Alle Gruppen mit ihren Lebensmitteln – fürs Stöbern ohne Suchbegriff.
   Innerhalb einer Gruppe alphabetisch: die Reihenfolge in der Liste oben
   ist thematisch sortiert, was beim Durchblättern von über hundert
   Gerichten niemandem hilft. */
function grundnahrungGruppen(){
  const gruppen = new Map();
  for (const lm of GRUNDNAHRUNG){
    if (!gruppen.has(lm.gruppe)) gruppen.set(lm.gruppe, []);
    gruppen.get(lm.gruppe).push(grundnahrungAlsLebensmittel(lm));
  }
  for (const liste of gruppen.values()){
    liste.sort((a, b) => a.name.localeCompare(b.name, 'de'));
  }
  return gruppen;
}
